.editorconfig

Add *.html file extension to editconfig

add html to .editorconfig

---

client/helpers/handlebars.js
client/views/comments/comment_item.js
client/views/nav/user_menu.js
client/views/posts/modules/post_rank.js
client/views/posts/post_submit.js
lib/helpers.js
lib/router/posts.js
lib/vote.js
packages/telescope-base/lib/base.js
packages/telescope-lib/lib/permissions.js
packages/telescope-notifications/lib/herald.js
packages/telescope-rss/lib/server/rss.js
packages/telescope-singleday/lib/client/templates/single_day.js
packages/telescope-singleday/lib/client/templates/single_day_nav.js
packages/telescope-singleday/lib/singleday.js
server/migrations.js
tests/jasmine/client/unit/commentItemSpec.js

Also combining can.upvote and can.downvote and deleting unused permissions function and random cleanup.

Cleaning up vote click handling functions and adding tests.

---

lib/publications.js
packages/telescope-notifications/i18n/en.i18n.json
packages/telescope-notifications/lib/client/templates/post_subscribe.html
packages/telescope-notifications/lib/client/templates/post_subscribe.js
packages/telescope-notifications/lib/client/templates/user_subscribed_posts.html
packages/telescope-notifications/lib/client/templates/user_subscribed_posts.js
packages/telescope-notifications/lib/herald.js
packages/telescope-notifications/lib/notifications.js
packages/telescope-notifications/lib/server/notifications-server.js
packages/telescope-notifications/lib/server/publications.js
packages/telescope-notifications/lib/subscribe.js
packages/telescope-notifications/package.js

Ref #452.
- Subscribe/Unsubscribe post
- When new comment added on user's subscribed posts, user receive notification.
- Show subscribed posts on user's profile
- Author can't subscribe own post (already sends notification)
- Change new comment's email notification subject, if post is subscribed post (not own post)
- Save subscriber count on post.

Subscribe post

---

client/views/common/layout.js
client/views/nav/nav.js
tests/jasmine/client/integration/mobileNavSpec.js

Fixes #719. Allowing mobile nav to close if user clicks anywhere outside of it

---

lib/analytics.js

I couldn’t get Google Analytics to work using the Tracking ID in the
admin section until I changed the code to this.

Fix Google Analytics

---

server/users.js

Added missed semicolons and commented mindless & unused functions

Small improvements

---

i18n/bg.i18n.json
packages/telescope-singleday/i18n/bg.i18n.json
packages/telescope-singleday/package.js
packages/telescope-tags/i18n/bg.i18n.json
packages/telescope-tags/package.js

Updated the main bg.18n.json and also translated some packages to keep everything consistent.

More bulgarian translations

---

lib/vote.js
packages/telescope-base/lib/base.js
packages/telescope-base/package.js

As per the conversation here: https://github.com/TelescopeJS/Telescope/pull/797
* Changed votePowerEq to getVotePower.
* getVotePower now accepts both Numbers and Functions.
* getVotePower now throws an error when set to an object type which is not a function and cannot be converted to a Number.
* The "Method" callbacks are now performed before votes are processed.

Improvement on vote accesability through packages 2nd pass

---

lib/publications.js

- services.twitter.profile_image_url_https field wasn't being published

Fix broken twitter avatars

---

lib/publications.js

- didn't notice avatarOptions object last time
Thanks @saimeunt!

Fix broken twitter avatars (for real this time)

---

collections/posts.js

fixes #826
One first step to tackle global pollution! ;)
I hope this PR doesn't come over as an insult :)

missing `var` keyword for `defaultProperties`

---

lib/users.js

Looks like the cursor needs a Date object to work with

Fix: numberOfItemsInPast24Hours always returns 0

---

packages/telescope-tags/lib/server/hooks.js
packages/telescope-tags/package.js

Created PR for https://trello.com/c/yJIcIzuz/97-check-that-categories-are-real-categories-server-side

Validate post's categories on server.

---

client/views/comments/comment_edit.js
client/views/comments/comment_form.js

I tested Ctrl+Enter on Ubuntu machine.
Please test it on Mac.

Submit comment when press Crtl/Cmd+Enter

---

packages/telescope-email/lib/server/email.js
packages/telescope-email/lib/server/templates/emailWrapper.handlebars

Color names changed in latest Telescope version but email package was not updated to reflect the change.

Change color names in email package

---

server/publications/single_post.js

Whatever reason, sometimes post in undefined. So we need check post existence before access to `userId`.
Close #915

check post existence before access on postUsers publication

---

packages/telescope-getting-started/lib/server/dummy_content.js
packages/telescope-migrations/lib/server/migrations.js

When starting with a fresh database a few items were out of date on the getting started package, this fixes all except for the default users do not have a gravatar image.

fix for nearly all of the getting started package issues

---

packages/telescope-posts/lib/routes.js

kept seeing these so figured i'd remove

cosmetic remove some trailing commas from telescope-posts

---

packages/telescope-core/i18n/en.i18n.json
packages/telescope-core/lib/client/templates/common/css.html
packages/telescope-core/lib/client/templates/common/css.js
packages/telescope-settings/lib/settings.js

This adds an "Extra CSS" settings field that adds that CSS to every page mentioned in #949. Any thoughts? Thanks!

Add Extra CSS

---

packages/telescope-migrations/lib/server/migrations.js
packages/telescope-newsletter/lib/newsletter.js
packages/telescope-newsletter/lib/server/cron.js

This adds an option for each day of the week to Newsletter Frequency. Let me know if you have any changes! :smile_cat:

Update newsletter schedule

---

packages/telescope-core/lib/client/templates/common/layout.html
packages/telescope-newsletter/lib/client/templates/newsletter_banner.html
packages/telescope-releases/lib/client/templates/current_release.html
packages/telescope-update-prompt/lib/client/templates/update_banner.html

and constrain current internal hero modules back into the max-width by wrapping them with .content-wrapper again

allow hero modules to be full width of viewport

---

packages/telescope-sitemap/lib/server/sitemaps.js

otherwise it'll hard crash on an unknown value, like "daily"

make sure the postView is a function

---

packages/telescope-tags/lib/callbacks.js

Fix bug that $set and $unset categories same time.

---

packages/telescope-sitemap/lib/server/sitemaps.js

As seen on this issue https://github.com/TelescopeJS/Telescope/issues/1173

Fixed url not defined in postPages[post.url] line 53

---

packages/nova-comments/lib/methods.js

This fixes the comment incrementing issue I made.

fix #1255 - add comment incrementing to Posts when adding a comment

---

packages/nova-base-components/lib/routes.jsx

Fixed missing App reference in routes.jsx

fix 404Error page

---

README.md

There was a typo error in the READM.md under **Files**

Collection typo error in README.md

---

README.md
sample_settings.json

Within the Facebook social logins settings `clientId` should be `appId`

Fix Facebook settings error in sample_settings.json and README.md

---

sample_settings.json

not work if only language, need set locale

set locale in settings

---

README.md

A link to Polish locale package

pl_PL locale

---

README.md

Syntax highlighting added (where missing) ✨

---

README.md

- git clone git@github.com:TelescopeJS/Telescope.git
+ git clone https://github.com/TelescopeJS/Telescope.git

little detail makes big difference for nob like me

---

README.md

new nova i18n package (de_DE)

---

packages/nova-users/lib/callbacks.js

- Update the options.email if/else if statement to include a section for Linkedin
- Update the displayName if/else if statement to include a section for Linkedin

Update callback.js to include Linkedin

---

README.md

Added link to Brazilian Portuguese (pt-BR) internationalization package repository to README.md

Added Brazilian Portuguese package to README.md

---

packages/nova-forms/lib/NovaForm.jsx

Hi,
This PR close #1471 , add key down event handler to NovaForm.

Add shortcut to submit form, close #1471

---

.eslintrc
.gitignore
package.json

- adds base eslint config and accompanying npm run script

add eslint with basic plugins and configuration. fixes #1470

---

packages/nova-base-components/lib/users/UsersAvatar.jsx

Nice in the commenters list of a PostItem.

Add username tooltip to user's avatar

---

prestart_nova.sh

Adding Check and/or preinstall Meteor
Please test it to confirm thanks

Adding Check and/or preinstall Meteor

---

packages/nova-categories/lib/custom_fields.js

i forgot to wrap custom fields object into an array.

Unable to assign category to a post (fix #1592)

---

prestart_nova.sh

Tested on a Linux install but gave an error now it's all fixed and tested

small fix for bash install meteor

---

packages/example-customization/lib/modules.js

I doubt the app will ever break because of those semi-colon omissions but I added them, just to be safe.

Semi-colon Updates

---

.meteor/versions

Fix for https://github.com/meteor/meteor/issues/8751

(update_version): package:dymanic-import from 0.1.0 -> 0.1.1 to fix 

---

packages/vulcan-forms/lib/Form.jsx

We added the `addToSubmitForm` function that's passed down to children of the form components a while ago. This adds two very similar functions that allow a component to add callbacks on form success and form failure.

Added failure form callbacks and success form callbacks to forms

---

packages/vulcan-users/lib/helpers.js

Fix for Users.getTwitterName()

---

sample_settings.json

A fix to #1691 issue related to a Mailchimp type error in newsletter component.
h/t @DSoe for the help.

Update sample_settings.json with new mailchimp schema properties

---

packages/vulcan-lib/lib/server/mutations.js

[fix] give default value to unset

[fix] give default value to unset

---

packages/vulcan-accounts/imports/ui/components/LoginForm.jsx
packages/vulcan-i18n-en-us/lib/en_US.js

Re-opening #1709 against devel. Still worked without any changes needed.

Display errors on password reset form

---

packages/vulcan-forms/lib/components/Form.jsx

I needed some kind of way to submit a form from a child component. However, a straightforward `submitForm` method in context didn't work, since I wasn't able to predict when my changes made via other functions such as `updateCurrentValues` would go through. 
The most elegant solution that I've found was to add an optional flag to `updateCurrentValues` that when set to true submits the form as soon as the values are set. It's not the most elegant solution, but I wasn't able to come up with a better one on the fly. Happy to change this if someone has better ideas.

Added submit option to `updateCurrentValues` in Form.jsx context

---

packages/vulcan-subscribe/README.md

👋 
While adding subscriptions support for a custom collection I came across a couple of bugs in the documentation. Hopefully this patch brings the Readme in line with the actual functionality.

fixed some minor bugs in the documentation for subscribeMutationsGenerator

---

README.md
package.json
prestart_vulcan.js

Correct prescript for its operation in windows, making it compatible on all three platforms: linux, MacOS and Windows.
I add Vulkan's logo on the console.

Correct prescript for its operation in windows, making it compatible on all three platforms: linux, MacOS and Windows.

---

packages/vulcan-forms/lib/components/Form.jsx
packages/vulcan-forms/lib/components/FormSubmit.jsx

- Pass all properties of fieldSchema.form on to the form component
- Restore missing delete link

Changes to support vulcan-material-ui

---

packages/vulcan-core/lib/modules/default_resolvers.js
packages/vulcan-lib/lib/modules/callbacks.js
packages/vulcan-lib/lib/modules/debug.js

A few changes to support debugGroup() and debuggGroupEnd() in addition to debug().
Also makes use of those in the callback & resolver logs, in addition to some colors.

Debug Groups & Colors

---

packages/vulcan-lib/lib/server/apollo_server.js

Some eslint formatting crept in, bloats the diff, but since it's just following the eslintrc, it should be done sooner or later anyway ;)

Allow the ApolloEngine LogLevel to be set via the settings

---

packages/vulcan-voting/lib/modules/vote.js

This PR fixes two bugs in voting: 
1. Voting doesn't properly update the score and the active status of an item
2. Cancelling a vote deletes *all* votes from an item, not just your own

Fixed voting bugs

---

packages/example-forum/lib/modules/comments/schema.js
packages/example-forum/lib/modules/posts/schema.js

The latest major updates changes what fields show up in the graphql schema. This adjusts example-forum appropriately.

Fixed graphQL schema for example-forum

---

packages/vulcan-voting/lib/modules/make_voteable.js

I couldn't get allVotes, after talking to habryka he said this could be a bug. This code works for me, please take a look.

fix allVotes resolveAs

---

packages/vulcan-core/lib/modules/components/Card.jsx

Same here made the mistake to not look at the branch.

Revert "showEdit on Card"

---

packages/vulcan-voting/lib/modules/make_voteable.js

revert allVotes

---

packages/vulcan-forms/lib/components/FormComponent.jsx

I just implemented @justinr1234 fix for the select component.

optionsAsStrings was not defined

---

packages/vulcan-accounts/package.js
packages/vulcan-admin/package.js
packages/vulcan-cloudinary/package.js
packages/vulcan-core/package.js
packages/vulcan-debug/package.js
packages/vulcan-email/package.js
packages/vulcan-embed/package.js
packages/vulcan-events-ga/package.js
packages/vulcan-events-intercom/package.js
packages/vulcan-events-internal/package.js
packages/vulcan-events-segment/package.js
packages/vulcan-events/package.js
packages/vulcan-forms-tags/package.js
packages/vulcan-forms-upload/package.js
packages/vulcan-forms/package.js
packages/vulcan-i18n-en-us/package.js
packages/vulcan-i18n-es-es/package.js
packages/vulcan-i18n/package.js
packages/vulcan-lib/package.js
packages/vulcan-newsletter/package.js
packages/vulcan-payments/package.js
packages/vulcan-routing/package.js
packages/vulcan-subscribe/package.js
packages/vulcan-users/package.js
packages/vulcan-voting/package.js

updated all vulcan packages to meteor 1.6.1. Tested as well and it works locally.

packages update to meteor 1.6.1

---

sample_settings.json

https://github.com/VulcanJS/Vulcan/blob/master/packages/vulcan-events-ga/lib/client/ga.js#L28

Fix sample_settings.json for Google Analytics

---

packages/vulcan-core/lib/modules/containers/withUpsert.js
packages/vulcan-core/lib/modules/index.js
packages/vulcan-lib/lib/modules/collections.js

Allows to search by any valid mongo search

#1865 Fix upsert

---

packages/vulcan-payments/lib/server/integrations/stripe.js

Allow modifying data sent to stripe before it is sent. Allow callbacks to hook into the raw charge data immediately after it goes to stripe.

Add stripe callbacks

---

packages/vulcan-i18n-es-es/lib/es_ES.js

Disclaimer: I haven't tested all the translation deeply. 
I found one missing.

Missing es-ES translation

---

packages/vulcan-i18n-fr-fr/lib/fr_FR.js

Don't know why that string was missing

add error_incorrect_password to FR package

---

packages/vulcan-forms/lib/components/Form.jsx

Props don't get recomputed when they change causing stale values to show up. This happens if you change routes on your page (lets say PostsSingle) without reloading the page. This will cause react to not re-load the components and so therefore since these values are only constructed in the constructor, they will never be recomputed when the props change.

Fix Form props

---

packages/vulcan-lib/lib/server/query.js

runQuery->runGraphQL

---

packages/vulcan-forms/lib/modules/utils.js
packages/vulcan-lib/lib/modules/validation.js
packages/vulcan-users/lib/modules/permissions.js
packages/vulcan-users/lib/server/on_create_user.js

Allow the passing of arrays with both functions and strings to the permission system

---

README.md

Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/vulcan❤️
It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [more info](https://github.com/opencollective/opencollective/wiki/Github-banner). See how it looks on this [repo](https://github.com/apex/apex#backers).
You can also add a postinstall script to let people know after npm|yarn install that you are welcoming donations (optional). [More info](https://github.com/OpenCollective/opencollective-cli)
You can also …

Open Collective Updates

---

packages/vulcan-accounts/imports/components.js
packages/vulcan-accounts/imports/routes.js
packages/vulcan-accounts/imports/ui/components/VerifyEmail.jsx
packages/vulcan-i18n-en-us/lib/en_US.js
packages/vulcan-i18n-es-es/lib/es_ES.js
packages/vulcan-i18n-fr-fr/lib/fr_FR.js
packages/vulcan-users/lib/server/urls.js

Adds support for email address verification to Vulcan, which lost it in the last Meteor version upgrade.

Add support for email address verification.

---

packages/vulcan-lib/lib/server/apollo_server.js

Pass request headers through context 

---

packages/vulcan-core/lib/modules/containers/withMulti.js

After a create mutation, the created document is added multiple times to lists using `withMulti` HOC.
`withMulti` update reducer is executed once for every observed query. So, when performing a create mutation the document is added to the results set as many queries being observed.
1. Render two components decorated with `withMulti` HOC for the same type (so, two lists that retrieve the same list of documents).
2. Perform a `createMutation` with a new document that should be added to those lists.
3. The document will be added twice will be added into every list
4. On the next polling, the list will be updated with server data and the duplicated document will disappear
Only add the document to the results set if is not already there.

Add only document once on withMulti query reducer

---

packages/vulcan-accounts/imports/ui/components/LoginFormInner.jsx

resetStore: Store reset while query was in flight.
https://github.com/apollographql/apollo-client/issues/2919#issuecomment-378790109

fix bug preflight from apollo

---

README.md

- Fix broken link to the contributors
- Fix broken anchors to opencollective page
- Fix sponsors list display

Fix OpenCollective part of readme

---

packages/_boilerplate-generator/package.js
packages/vulcan-lib/lib/modules/collections.js

Maybe there are use cases where you might want to use `terms.query` while not setting searchable to true?

Warn when no searchable field is set and terms.query is set

---

packages/vulcan-core/lib/modules/components/MutationButton.jsx

- update loading state on mutation error
- prevent unknown props warning

Mutation button small fixes

---

packages/vulcan-lib/lib/modules/collections.js

This adds sync collection creation hooks and postfixes aysnc collection hooks with `.async`
- *.collection
- ${collectionName}.collection
- *.collection.async (currently named '*.collection')
- ${collectionName}.collection.async (currently named ${collectionName}.collection)

added collection creation hook

---

packages/vulcan-forms/lib/components/Form.jsx
packages/vulcan-forms/lib/components/FormNestedArray.jsx
packages/vulcan-forms/lib/components/FormNestedItem.jsx

This allows you to supply minCount and maxCount on the form fields.
Supplying min count will automatically add nested form fields.
Hides ui when max and min are reached.
#2138

add minCount and maxCount to SmartForm nested arrays

---

packages/vulcan-routing/lib/server/routing.jsx

This fixes `Helmet` throwing an error when testing.
[github issue](https://github.com/nfl/react-helmet/issues/238)

fixed helmet for testing

---

packages/vulcan-forms/lib/components/FormError.jsx

forgot to add variable

---

packages/vulcan-accounts/imports/ui/components/Field.jsx

Fix const assignment.

---

packages/vulcan-email/lib/server/email.js

There ain't no wrapper anywhere, so don't require one.
(Sth. to add to the docs?)

Add wrapperless Emails.

---

packages/vulcan-ui-bootstrap/lib/components/forms/Select.jsx

Shouldn't it be this way around?

Fix labeling in select component.

---

packages/vulcan-core/lib/modules/components/Datatable.jsx

As well as other modal properties

make Datatable edit modal title customizable

---

packages/vulcan-forms/lib/components/FormNestedArray.jsx

Hey !
Currently we have an *itemIndex* which is use to identify each items modify them.
If we want to use *itemIndex* in our beforeComponent to have an Array text like:
" TEAM
Member 1
Member 2
Member 3
Member 4
Member 5
Member 6
"
We will have some bugs when we will delete some items.
Like if I delete: 2 and 4, and add 2 more, I'll have:
" TEAM
Member 1
Member 3
Member 5
Member 6
Member 7
Member 8
"
So, I'm adding a *visibleItemIndex* which should solve this problem.
Now, it's working when I delete the lasts members and add new, but It still have some problems when I delete some inner, like I can have:
" TEAM
Member 1
Member 3
Member 5
Member 4
Member 5
Member 6
"
I think it's just one little think but I didn't find, maybe someone can improve this commit and merge it.

add visibleItemIndex function/prop in FormNestedArray

---

packages/vulcan-forms/lib/components/FormNestedArray.jsx

With this modification we can pass a custom footer for the array forms.

FormNestedArray Footer modification via props fixing

---

packages/vulcan-core/lib/modules/components/Card.jsx
packages/vulcan-core/lib/modules/components/Datatable.jsx
packages/vulcan-forms/lib/components/Form.jsx
packages/vulcan-forms/test/components.test.js
packages/vulcan-i18n/lib/modules/provider.js
packages/vulcan-i18n/lib/modules/shape.js
packages/vulcan-i18n/test/provider.test.js
packages/vulcan-lib/lib/modules/intl.js
packages/vulcan-lib/test/intl.test.js

This will allow projects to replace vulcan:intl and use the full react-intl

Move getLabel from vulcan:intl to vulcan:lib

---

packages/vulcan-email/lib/server/email.js
packages/vulcan-lib/lib/modules/utils.js

Add two new email template vars: rootUrl and logoReverseUrl

Email template vars

---

packages/vulcan-ui-material/lib/components/forms/base-controls/MuiCheckboxGroup.jsx

Add functionality to MuiCheckboxGroup to respect maxCount schema property

MuiCheckboxGroup maxCount

---

packages/vulcan-accounts/imports/ui/components/LoginFormInner.jsx

- In some instances, for example post sign-up, the `then` clause is never called. Apollo Client now has the `onResetStore` function to solve this.
- `resetStoreAndThen` and `postLogInAndThen` essentially both just call `resetStore` and then the next hook. Using them both one after the other seems superfluous
- In `SignUp` I moved `self.setState({ waiting: false });` and `self.clearDefaultFieldValues();` higher to reduce the chance of React errors if the user is redirected in the `onPostSignUpHook` hook

ResetStoreCallbackNotBeingRun

---

.gitignore
.meteorignore
.storybook/addons.js
.storybook/decorators/MaterialUIDecorator.js
package.json
packages/vulcan-core/lib/modules/components/Avatar.jsx
packages/vulcan-forms/lib/components/FormNestedArray.jsx
packages/vulcan-i18n-en-us/lib/en_US.js
packages/vulcan-i18n-es-es/lib/es_ES.js
packages/vulcan-i18n-fa-ir/lib/fa_IR.js
packages/vulcan-i18n-fr-fr/lib/fr_FR.js
packages/vulcan-ui-bootstrap/lib/stylesheets/style.scss
packages/vulcan-ui-material/lib/components/core/Avatar.jsx
packages/vulcan-ui-material/lib/components/index.js
packages/vulcan-ui-material/lib/components/ui/Button.jsx
packages/vulcan-ui-material/lib/modules/index.js
packages/vulcan-ui-material/lib/modules/sampleTheme.js
packages/vulcan-ui-material/lib/server/wrapWithMuiTheme.jsx
packages/vulcan-users/lib/modules/avatar.js
stories/vulcan.stories.js
yarn.lock

* Upgraded `@material-ui/core` to `^3.9.3`
* Added new material-ui `Avatar` component
* Normalized the parameters of the `Avatar` and `Button` components between ui-bootstrap and ui-material
* Updated the Storybook stories for `Avatar` and `Button` and added Storybook Knobs to be able to test all their properties

Storybook+Avatar+Button

---

packages/vulcan-accounts/imports/ui/components/LoginFormInner.jsx
packages/vulcan-ui-material/lib/components/accounts/AccountsForm.jsx
packages/vulcan-ui-material/lib/components/forms/FormGroupDefault.jsx
packages/vulcan-ui-material/lib/components/forms/FormGroupLine.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiInput.jsx
packages/vulcan-ui-material/lib/example/Header.jsx
packages/vulcan-ui-material/lib/modules/sampleTheme.js

* Error messages were not cleared during password change
* Accounts form success messages were colored red (update your theme to match the sample)
* Fixed class name of FormGroupHeader
* Made FormGroupHeaderLine more consistent with FormGroupHeader

MaterialUiMinorBugs

---

packages/vulcan-lib/lib/server/apollo-server/engine.js

Add support for Apollo Engine schemaTag in addition to apiKey

ApolloEngineSettings

---

packages/vulcan-forms/lib/components/FormComponent.jsx

Add support for Apollo Engine schemaTag in addition to apiKey

SimpleSchemaIntegerFieldType

---

packages/vulcan-redux/package.js
packages/vulcan-styled-components/package.js
packages/vulcan-test/package.js
packages/vulcan-ui-material/package.js
packages/vulcan-ui-material/readme.md

Updated out of date package version numbers in vulcan:redux, vulcan:styled-components, vulcan:test, and vulcan:ui-material

VersionNumberCorrections

---

packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSuggest.jsx

Fixed bug: MuiSuggest would not show all options even when showAllOptions property was set

MuiSuggestShowAllOptions

---

packages/vulcan-email/lib/server/email.js

Hi there!
I think it could be a good idea to have the possibility to add a props "from" in the Vulcan email.
What do you think ?

add from props

---

packages/vulcan-lib/lib/modules/utils.js

Convert an array of field options objects into an allowedValues array

add to utils a getSchemaFieldAllowedValues function

---

packages/vulcan-forms/lib/components/Form.jsx
packages/vulcan-forms/lib/components/FormComponent.jsx
packages/vulcan-forms/lib/components/FormGroup.jsx
packages/vulcan-forms/lib/components/FormNestedArray.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/mixins/component.jsx

In SmartForms, add support for prefilled props for nested array elements

PrefilledProps for form nested arrays

---

packages/vulcan-errors/lib/modules/errors.js

Add getUserPayload to vulcan:errors

ErrorsGetUserPayload

---

packages/vulcan-ui-material/lib/components/bonus/LoadMore.jsx
packages/vulcan-ui-material/lib/components/forms/FormComponentInner.jsx
packages/vulcan-ui-material/lib/components/forms/FormGroupDefault.jsx
packages/vulcan-ui-material/lib/components/forms/FormGroupLine.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiFormControl.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiFormHelper.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiInput.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiPicker.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiRadioGroup.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiRequiredIndicator.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSelect.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSuggest.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSwitch.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/mixins/component.jsx
packages/vulcan-ui-material/lib/components/index.js

* Add indicator for required fields
* Fix bug in LoadMore component
* Allow styling of disabled input

MaterialUiMinorChanges5

---

packages/vulcan-core/lib/modules/containers/create.js
packages/vulcan-core/lib/modules/index.js
packages/vulcan-core/test/containers/mutations.test.js

fix multiQuery update error with non null selector

---

README.md

Looks like these links is outdated for quite time already 😄

Update of outdated links in README.md

---

packages/vulcan-ui-material/readme.md

Change readme material-ui versions

add @material-ui packages

---

.meteor/packages
.meteor/versions
package-lock.json
packages/vulcan-redux/lib/client/main.js
packages/vulcan-redux/lib/client/setupRedux.js
packages/vulcan-redux/lib/modules/reducer.js
packages/vulcan-redux/lib/modules/redux.js
packages/vulcan-redux/lib/server/main.js
packages/vulcan-redux/lib/server/setupRedux.js
packages/vulcan-redux/package.js
packages/vulcan-redux/test/client/index.js
packages/vulcan-redux/test/client/initialState.test.js
packages/vulcan-redux/test/index.js
packages/vulcan-redux/test/server/index.js
packages/vulcan-redux/test/server/initialState.test.js
packages/vulcan-redux/test/server/initialStateWithValue.test.js

Redux tests for setupRedux(initialState)

---

packages/vulcan-users/lib/modules/permissions.js

Pass document to Users.isMemberOf in permissions.js in

---

packages/vulcan-core/lib/modules/containers/create2.js

Change `multiQueryUpdater` to use `client.writeQuery` which "leads to watched queries being re-broadcast" according to apollo team here: https://github.com/apollographql/apollo-client/issues/4398
Tested this on our app and it seems to fix the issue we were seeing with relevant queries not updating as expected.

use apollo client in multiqueryupdater to broadcast to watched queries

---

stories/ref.stories.js

This story demonstrates a solution to https://github.com/VulcanJS/Vulcan/issues/2449.

Add story to demonstrate ref forwarding in Vulcan Components

---

packages/vulcan-lib/lib/modules/validation.js

The full document must be passed to validateDocumentPermissions even on a partial update because permission logic may rely on other fields in the document. Even the core 'owners' behavior relies on this, and will fail if 'owners' isn't included in the document passed to `Users.canUpdateField`

Pass full doc and document to validate to validateDocumentPermissions

---

packages/vulcan-ui-material/lib/components/core/Datatable.jsx

The `columns` in the data were not populating correctly so I grabbed https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-core/lib/modules/components/Datatable/DatatableContents.jsx#L9 from the core DatatableContents component.
Also I added getCollection so `collectionName` can be specified on the collections.
Fixes  #2475

datatable fix for material ui

---

packages/vulcan-ui-material/lib/components/core/Datatable.jsx

With out this dot the app will crash with an error

fix call to sortBy in Datatable.jsx

---

packages/vulcan-ui-material/lib/components/forms/base-controls/MuiCheckbox.jsx
packages/vulcan-ui-material/lib/components/forms/controls/Checkbox.jsx

Before any checkbox in mui was a switch

add switch/checkbox alternative in material ui

---

packages/vulcan-lib/lib/modules/mongoParams.js

Before, if your input was
{_gte : 1, _lte : 5} 
your output wqs
{$gte:1}
now it is
{$gte:1, $lte:5}

bugfix for the input api so it can accept more than one input for a samme field

---

README.md

Use Meteor's version of npm over system default

---

packages/vulcan-core/lib/modules/decorators/radiogroup.js

using makeRadiogroup will give you an error as the allowedValues check is field and not on the arrayItem

fix allowed values for radiogroup

---

packages/vulcan-ui-material/lib/components/core/Card.jsx

Currently ui-material Card component will crash the app
This is a direct copy of the vulcan:core's Card component canUpdate to fix the issue

add new update check api to ui-material Card.jsx

---

packages/vulcan-events-segment/lib/client/segment-client.js

Don't load segment client code if `segment.clientKey` setting is not defined.

SegmentClientFix

---

packages/vulcan-ui-material/lib/components/bonus/LoadMore.jsx
packages/vulcan-ui-material/lib/components/bonus/ScrollTrigger.jsx

* Added `scroller` prop which defaults to `window`, but can be set to the ref of another element
* Refactored `LoadMore` and `ScrollTrigger` for more reliable performance

MuiScrollTriggerUpgrades

---

packages/vulcan-forms/lib/components/Form.jsx
packages/vulcan-forms/lib/components/FormComponent.jsx
packages/vulcan-forms/lib/components/FormError.jsx
packages/vulcan-forms/lib/components/FormGroup.jsx
packages/vulcan-i18n-en-us/lib/en_US.js
packages/vulcan-i18n-es-es/lib/es_ES.js
packages/vulcan-i18n-fa-ir/lib/fa_IR.js
packages/vulcan-i18n-fr-fr/lib/fr_FR.js

* SmartForm
* Enabled internationalizing field options labels even when the field schema `options` prop is a function
* Added `fieldName` to parameters passed to function field schema props
* Fixed concurrency bug in `clearFieldErrors()`
* Added new `clearFormCallbacks()` function to the Form context (callbacks tend to accumulate over time)
* Fixed bug in `updateCurrentValues()`: `cloneDeep` would be very slow sometimes, depending what was in `prevState`
* Fixed bug in `refetchForm()`: `this.props.data` has been removed
* FormComponent
* Fixed bug: the component would not update when the `help` prop changed
* `handleChange()` now only updates the value if it's actually changed
* `handleChange()` now clears the field error
* FormError
* Fixed bug: `defaultMessage` would never be displayed …

SmartFormEnhancements

---

packages/vulcan-ui-material/lib/components/bonus/TooltipButton.jsx
packages/vulcan-ui-material/lib/components/bonus/TooltipIntl.jsx
packages/vulcan-ui-material/readme.md

* Added new props: `danger` and `cursor`
* Added new value for `type` prop: `menu`

TooltipButtonUpgrades

---

packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSuggest.jsx

* Wrapped option icon in ListItemIcon component
* Fixed bug: `MuiSuggest` would not accept or display values that don't match an option value, even when `limitToList` was false
* Numerous other bug fixes and refactoring

MuiSuggestUpgrades

---

packages/vulcan-ui-material/lib/components/forms/base-controls/MuiInput.jsx

* MuiInput now supports an empty label and adjusts the spacing accordingly
* Other refactoring

MuiInputWithNoLabel

---

packages/vulcan-ui-material/history.md
packages/vulcan-ui-material/lib/components/forms/FormComponentInner.jsx
packages/vulcan-ui-material/lib/components/forms/FormGroupDefault.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/EndAdornment.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiCheckboxGroup.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiPicker.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSelect.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/MuiText.jsx
packages/vulcan-ui-material/lib/components/forms/controls/Select.jsx
packages/vulcan-ui-material/lib/components/theme/ThemeStyles.jsx
packages/vulcan-ui-material/lib/modules/sampleTheme.js
packages/vulcan-ui-material/readme.md

* Minor changes and bug fixes in Material UI components
* Updated `history.md` and `readme.md`
* Fixed bug: `FormGroupDefault` would not respect `collapsible` prop
* Fixed bug: `clear-enabled` class has been renamed `has-value` everywhere except `EndAdornment`

MaterialUiMinorChanges8

---

packages/vulcan-core/lib/modules/containers/currentUser.js

* `currentUser` HoC/Hook now returns an extra parameter: `currentUserRefetch`

CurrentUserRefetch

---

packages/vulcan-core/lib/modules/containers/multi.js
packages/vulcan-core/lib/modules/containers/multi2.js
packages/vulcan-forms/lib/components/Form.jsx
packages/vulcan-forms/lib/components/FormComponent.jsx
packages/vulcan-forms/lib/components/FormWrapper.jsx
packages/vulcan-lib/lib/modules/intl.js
packages/vulcan-lib/lib/server/default_resolvers.js

Made minor formatting changes to comply with linting rules.

Minor Formatting Oct 2020

---

packages/vulcan-lib/lib/client/apollo-client/apolloClient.js
packages/vulcan-lib/lib/client/apollo-client/links/error.js
packages/vulcan-lib/lib/client/apollo-client/links/http.js
packages/vulcan-lib/lib/server/apollo-ssr/apolloClient.js

Updated additional import statements to use Apollo Client 3

Apollo Client 3 Import Fixes

---

packages/vulcan-lib/lib/server/debug.js

Useless logs annoy me, especially when they happen at every refresh of the server; so I've written some checks to only write the file and log when necessary.
I've also changed the logged message for more precision.

only Write and log graphql schema when different from existing file

---

packages/vulcan-ui-material/lib/components/forms/base-controls/FormInput.jsx

Form Component New Names Fix

---

packages/vulcan-ui-material/lib/components/forms/base-controls/FormInput.jsx
packages/vulcan-ui-material/package.js

* Fixed bug in `FormInput`
* Fixed package version number regression

Form Component New Names Fix 2

---

packages/vulcan-i18n-en-us/lib/en_US.js
packages/vulcan-i18n-es-es/lib/es_ES.js
packages/vulcan-i18n-fa-ir/lib/fa_IR.js
packages/vulcan-i18n-fr-fr/lib/fr_FR.js

* Changed {value} variable to {operationName}

Fix error message for app.operation_not_allowed

---

packages/vulcan-lib/lib/modules/intl.js

* Refactored intl function getString() for better readability
* Added docs and comments to explain the code

getString Refactor And Document

---

packages/vulcan-ui-material/lib/components/forms/base-controls/FormHelper.jsx
packages/vulcan-ui-material/lib/components/forms/base-controls/FormInput.jsx
packages/vulcan-ui-material/lib/components/forms/controls/Number.jsx

* Fixed bug: Decimal numbers were near impossible to enter in Number form component
* Added scrub function to Number input to only allow valid characters to be entered
* Fixed bug: Text input "characters remaining" would conflict with help text

Material UI Number input

---

packages/vulcan-core/lib/modules/components/App.jsx
packages/vulcan-lib/lib/server/apollo-server/context.js

* Refactored intl function getString() for better readability
* Added docs and comments to explain the code

Get string refactor and document

---

packages/vulcan-core/lib/modules/components/Card/Card.jsx
packages/vulcan-ui-material/lib/components/bonus/TooltipButton.jsx

* Export `Card` component
* Clarify prop types and export `TooltipButton` component

Material UI minor changes 01-2021

---

packages/vulcan-core/lib/modules/containers/withMessages.js
packages/vulcan-ui-material/lib/components/core/Flash.jsx

* Fixed bugs in flash messages using reactive state

Flash messages bug fixes

---

packages/vulcan-core/lib/modules/containers/create.js
packages/vulcan-core/lib/modules/containers/create2.js

When updating a document with the smartform and some error was thrown, no warning appeared because of the lines I have changed.
I just added ?. checks so have not added tests

create functions add non null checks

---

packages/vulcan-ui-material/lib/modules/themes.js

Same as the PR before i had not seen this

update material ui imports

---

packages/vulcan-lib/lib/modules/graphql_templates/types.js

Fixing issue with delimiter of multiple interfaces
