.meteor/packages, .travis.yml, client/views/nav/nav.js, packages/telescope-theme-hubble/lib/client/scss/modules/_nav.scss, tests/jasmine/client/unit/navSpec.js
Using the jasmine package seemed like the best way to go because we'll want most of the testing modes. I added the travis file, but it doesn't quite work yet (see https://travis-ci.org/anthonymayer/Telescope). I don't think any other changes should be required of the travis file right now though because I'm controlling it all through https://github.com/anthonymayer/travis-ci-meteor-packages. Once I get that working I'll probably add a tag in the README too.
Mostly I'm looking for feedback on testing structure. I'm hoping that after we have a few more examples of these that we start making adding/updating tests a requirement of push requests. Getting feedback from either @sanjo and/or @samhatoum would be awesome too.
I also deleted some nav stuff that looked unused.
=> Adding nav client unit test

packages/telescope-newsletter/i18n/en.i18n.json, packages/telescope-newsletter/lib/newsletter.js, packages/telescope-newsletter/lib/server/cron.js, packages/telescope-newsletter/package.js
Adding newsletterTime setting.
Still todo
=> Adding newsletter time setting

packages/telescope-getting-started/content/read_this_first.md
When there's account set up yet, the navigation says Register instead of Sign-up. 
I've just updated the 'Read this First' steps accordingly.
=> Changed Sign-up to Register

packages/telescope-post-by-feed/lib/client/routes.js, packages/telescope-post-by-feed/lib/feeds.js, packages/telescope-post-by-feed/lib/server/fetch_feeds.js, packages/telescope-post-by-feed/package.js
I added category assignment by adding a field to the schema. You can assign multiple categories to an rss feed. It should work aslo without any category created or assigned. Also the feedId is now assigned to the post.
=> Added category assignment to feeds

client/views/common/layout.js
The `{{{extraCode}}}` helper [in the layout template][1] was not defined anywhere and was not outputting anything as a result.  This fixes that.
[1]: https://github.com/TelescopeJS/Telescope/blob/devel/client/views/common/layout.html#L18
=> extraCode helper in layout template was not defined

lib/vote.js, packages/telescope-base/lib/base.js, packages/telescope-base/package.js
This is a modification which adds various callback hooks for the voting system.
It adds the callbacks:
<pre><code>cancelUpvoteCallbacks
cancelDownvoteCallbacks
upvoteMethodCallbacks
downvoteMethodCallbacks
cancelUpvoteMethodCallbacks
cancelDownvoteMethodCallbacks
</code></pre>
To the existing callbacks of:
<pre><code>upvoteCallbacks
downvoteCallbacks
</code></pre>
The advantage of the Method callbacks over the original ones is that the original ones ran asynchronously server-side, wheras the Method callbacks will hold up the vote action until the code in the callbacks finishes, which may be useful in some cases, and they run on both the server and client.
The original names were left consistent for backwards compatibility, but it may be worth considering changing the names to something …
=> Improved vote accessability for packages

packages/telescope-newsletter/lib/server/mailchimp.js
Campaign.js trims the newsletter's subject to 15 words which is enough in most cases. Yet, I have had the case where 15 words are more than 150 characters and the Mailchimp campaign fails.
=> Mailchimp limits email subject to 150 characters

lib/vote.js
When we downvote an item or cancel one of its upvotes, we should decrese, not increase, the base score.
=> Correct base score calculation in vote.js

collections/posts.js
postAfterEditMethodCallbacks execution behaviour was copied straight away from postEditMethodCallbacks execution : perform a reduction on the post modifier by executing every callbacks.
Since postAfterEditMethodCallbacks is executed after the actual DB update, we don't need to alter the modifier because it won't be used, so we can use a plain forEach instead of a reduction.
We also need to pass the post ID to the callback (as second argument so it won't break existing callbacks) because there's no way to identify the post that was modified in the callback if we don't.
Other modification on line 560 is due to trailing whitespace auto removal in my code editor.
=> Refactor postAfterEditMethodCallbacks execution on server

packages/telescope-search/lib/client/routes.js
This fixes the bug in issue #825. User couldn't clear last character in search keyword because routes.js automatically sets it to be query string. We should check if user tries to clear last character before set searchQuery in Session.
=> fix bug where last character in search keyword couldn't be cleared

client/views/users/account/user_account.js, packages/telescope-lib/lib/permissions.js, server/users.js
=> Add userId param to changeEmail method

packages/telescope-invites/lib/server/publications.js
Replace Meteor.user() call in telescope-invites.
Fixes #853.
=> Use this.userId, not Meteor.user in publications

History.md, server/publications/single_comment.js, server/publications/single_post.js
The screencast below shows the performance [problem I've highlighted on Crater](https://crater.io/comments/NJKs8Skwt7L4ALEt4):
This PR hopefully fixes that. I can't test at the moment due to [fourseven:scss not installing on Windows](https://github.com/TelescopeJS/Telescope/issues/859) and a similar problem with npm-bcrypt:
> => Meteor 1.1-rc.0 is available. Update this project with 'meteor update'.
=> Errors prevented startup:
>    While checking for fourseven:scss@1.0.0:
error: No compatible build found
>   While checking for npm-bcrypt@0.7.8_1:
error: No compatible build found
> => Your application has errors. Waiting for file change.
=> Improve comments loading performance on long threads

collections/posts.js
This PR unifies posts after submit/edit hooks.
"After" hooks should both be executed only on the server and asynchronously (to avoid holding up the client).
They don't need to modify either the post or the modifier because they happen after insert/update, the after submit hook gets passed the post and the after edit hook gets passed both the modifer and the modified post (this allows fine diffing between the two to take actions only if a particular field was modified).
Shouldn't break anything because it extends the existing API without modifying expected behaviour.
=> Unify posts hooks

client/views/posts/post_submit.js
The autoform docs specify that you should name your hook after the form type, not after the name of the method.
https://github.com/aldeed/meteor-autoform#callbackshooks
=> Fix a bug where the post submit autoform hook wasn't called

packages/telescope-comments/lib/client/templates/comment_submit.js, packages/telescope-comments/lib/comments.js, packages/telescope-migrations/lib/server/migrations.js
This allows childComments to know what the top most parent comment is by adding a topLevelCommentId to each childComment.
=> Add topLevelCommentId field to comments.

Dockerfile
Hi,
I've added a Dockerfile to telescope. With we can deploy Telescope with docker very easily, officially. There are few more steps for to do this.
* Create an account an Docker Hub: https://hub.docker.com/account/signup/ (May be an organization called telescope)
* Then click on the automated build as shown below to setup the automated build for every git-push
In that, you can target different branch to tag version. I prefer this way
* telescope/telescope:latest - master branch
* telescope/telescope:devel - devel branch
May be not everyone want to deploy telescope as a docker image, since telescope needs some customization before deploy. (Themes, etc)
But this would be great for quick deployment or showcasing things around.
=> Add Docker deployment support

packages/telescope-settings/lib/server/publications.js
The publication was supposed to be removing private fields from the published data, but the schema object was undefined and all properties were being published as a result.
=> fix settings publication to hide private fields (take 2)

packages/telescope-singleday/lib/client/templates/single_day_nav.js
I think it needs this to avoid the timezone affecting the diff. It was displaying the Today label for tomorrow.
=> Added .startOf('day'); to `today` variable

packages/telescope-posts/lib/client/templates/modules/post_avatars.html
Added a title attribute to the avatar links to give an overview who has posted on a topic even if no avatars are available. This should display the Displayname of a user on hovering over an avatar.
=> Title Links on Avatars

packages/telescope-email/lib/server/email.js
There is a broken link inside the new user account email notification.
Whenever I receive a notification about a new user account, the link to the user account looks something like `http:///users/john-ferguson` instead of `https://projectsafe.news/users/john-ferguson`.
```html
<span style="font-size:18px;font-weight:bold;line-height:1.5;margin:0">
A new user account has been created:
<a href="http:///users/john-ferguson" style="color:#5593d7;font-weight:bold;text-decoration:none" target="_blank">
SAFEcrossroads
</a>
</span>
```
This PR fixes the issue.
```javascript
Users.getProfileUrl = function (user, isAbsolute) {
if (typeof user === "undefined") {
return "";
}
var isAbsolute = typeof isAbsolute === "undefined" ? false : isAbsolute; // default to false
var prefix = isAbsolute ? …
```
=> use absolute URL for Users.getProfileUrl

packages/telescope-rss/lib/server/routes.js, packages/telescope-rss/lib/server/rss.js
Hey!
I'm pushing posts from Telescope into Hipchat via Zapier RSS. We wanted to have categories post into specific Hipchat rooms instead of all into the same room. We've also had comments that people would like to select categories to subscribe to in the newsletter.
Hope this helps! Let me know if you have any feedback. I'm not familiar with Meteor.
=> Added a RSS route that returns posts filtered by category

packages/telescope-sitemap/lib/server/sitemaps.js
This fixes the current error when using the telescope-sitemap package by using the Posts.getLink(post) function that all of the routers use, plus getting the slug field for all posts makes the url's pretty & SEO friendly.
=> Correctly get url for sitemap using slug

packages/telescope-theme-hubble/lib/client/scss/modules/_posts.scss
Via CSS, I've showed the share button and hide the discuss icon on the post's page. Basically, the share button replaces the real estate of the discuss icon because we are already on the post's page, and we still have the comment link/count in the post's meta.
=> Show Share button on desktop version

packages/telescope-email/lib/server/templates/emailWrapper.handlebars, packages/telescope-newsletter/lib/server/campaign.js, packages/telescope-newsletter/lib/server/templates/emailPostItem.handlebars
Trim HTML-stripped version of the post body, because trimming `post.body` gives unexpected results.
e.g.
If post.body was `### Title\n\n * list item 1 * list item 2`, it appears in the newsletter as  `<h3 id="title-list-item-">Title * list item…</h3>`
=> Improve newsletter

packages/telescope-core/lib/client/templates/forms/urlCustomType.js
This allows you to remove a URL when editing, and fixes #1012.
Looks like it had something to do with the bootstrap-url valueOut function not returning a value when blank.
Let me know if you have any changes. Thanks!
=> Fix Removing URL on Edit

packages/telescope-notifications/lib/callbacks.js, packages/telescope-post-by-feed/lib/server/fetch_feeds.js, packages/telescope-users/lib/callbacks.js, packages/telescope-users/lib/helpers.js
A method to fetch users who are admins is defined in [telescope-users/lib/helpers.js](https://github.com/TelescopeJS/Telescope/blob/88b5afc65047300999ddb961492c095be3d886ac/packages/telescope-users/lib/helpers.js#L277-L279), but it wasn't used consistently.
Update ``telescope-notifications`` and ``telescope-post-by-feed`` to use the abstraction rather than querying for isAdmin directly.  To support their use, add an ``options`` parameter to ``Users.adminUsers`` that can be used to provide field/limit options to the lookup.
=> Use abstraction of adminUsers consistently

packages/telescope-i18n/i18n.js, packages/telescope-posts/lib/posts.js
The schema internationalization needs to happen on the collection layer, not schemas.
Why is that so ? `Posts.schema` is agnostic to changes made by `Posts.addField`, because it uses `Posts.attachSchema` under the hood, leaving `Posts.schema` untouched.
This means that `Posts.schema.internationalize()` won't take added fields into account, which is problematic.
That's why I moved the `Posts.schema.internationalize` logic to the collection layer instead of the schema layer, because we can use collection2 `simpleSchema` method which returns the aggregated schema using to manage the collection.
Then we need to wrap up `Posts.internationalize()` inside a `Meteor.startup` call to make it run explicitly after every call to `Posts.addField`.
The PR only makes this fix for `Posts`, but it needs …
=> Fix schema i18n by moving internationalize to collections

packages/telescope-comments/lib/helpers.js
This is to ensure that in notifications, those users who do not have a username,
are still displayed using their display name.
This is required because certain users are missing user names (caused by the usage of
the social sign-up options which does not create a username)
=> replaced getUserName with getDisplayName for comments

packages/telescope-lib/lib/client/template_replacement.js, packages/telescope-lib/lib/custom_template_prefix.js, packages/telescope-lib/package.js
Separate template replacement from adding the initial "custom" prefix,
so that server-side templates (namely e-mails) can also have overrides.
=> Fix e-mail template overrides by adding the "custom" prefix server-side

packages/telescope-posts/lib/client/templates/post_submit.js
`if (error.error === 603) {...}` is always resulting false even error.error is "603" and the codes insides is never executed. 
It is because error.error is string "603".
It is need double quote to be  `if (error.error === "603") {...}`
=> Fixing `(error.error === 603)` always results false

packages/telescope-embedly/lib/client/autoform-postthumbnail.html
Add an empty alt attribute for <img tag , to fixing broken empty image placement in firefox
as suggested by @bharatjilledumudi
=> Fixing issue #1170

packages/telescope-posts/lib/methods.js, packages/telescope-posts/lib/posts.js, packages/telescope-posts/lib/server/publications.js, packages/telescope-posts/package.js
Publications are blocking and there is really no reason to, making the post publications synchronous doesn't help anything. I used the `meteorhacks:unblock` package and it seems to be helping load times on Crater so far.
Hattip to @arunoda for his help on this.
=> Unblock publications

packages/telescope-tags/lib/helpers.js
If using slug, when we edit the category, the slug changes and the counter
become 0 until we refresh the browser. I think it's better if we stick with
_id because _id is not changing.
=> Set counter name to category id instead of category slug

packages/telescope-users/lib/callbacks.js
Most sites, when you log in with a 3rd party OAuth provider, will fill in whatever possible fields when making a new account.  Mirroring the capability here.
I was unable to test with Weibo due to not having a Chinese phone number, but I tested with the other external services mentioned [here](http://docs.meteor.com/#/full/meteor_loginwithexternalservice).  The ones I didn't add support for do not provide the email address back by default.
=> supply default email based on 3rd party login, if possible

packages/nova-getting-started/lib/server/dummy_content.js
On starting with the Nova version, there's this persistant ` Error: Username already exists. [403]` issue. This PR fixes that by checking if there are users first.
=> Fix Username already exists issue [403]

.meteor/packages, .meteor/versions, packages/base-components/package.js
New version doesn't have a dependency on the Meteor react-runtime package so works well with the NPM react version.
There are other packages (utilities:react-list-container, utilities:react-form-containers) in Telescope that do use the react-runtime so until those are updated the local react-runtime package is still needed as an override to remove the duplicate React issue.
=> update to version of alt:react-accounts* that doesn't depend on react-runtime

packages/telescope-notifications/lib/notifications.js
Without this, the following bug would happen:
When a user adds a comment to a post with a subscriber that is not otherwise notified, the notification doesn't get sent and the server repots the following error: "Exception in defer callback: Error: [Can't start Herald.escalate: TypeError: undefined is not a function]" when trying to notify a subscriber of a comment.
=> fixing typo in newCommentSubscribed notification

.meteor/versions, packages/nova-base-components/lib/posts/PostPage.jsx, packages/nova-base-components/lib/users/AccountsMenu.jsx, packages/nova-base-components/lib/users/UserMenu.jsx, packages/nova-base-components/package.js, packages/nova-users/lib/server/create_user.js
Roadmap task : https://trello.com/c/nhjQ4TaI/20-comments
Here is what I have done @SachaG:
1. I have checked if there is a `currentUser` or not :
**=>** Render `<CommentNew />` if the user is logged in, render `<Accounts.ui.LoginForm />` if he is not logged in.
2. I have realized that @timbrandin moved [studiointeract:react-accounts-ui](https://atmospherejs.com/studiointeract/react-accounts-ui) to [std:accounts-ui](https://atmospherejs.com/std/accounts-ui).
**=>** Switch from `studiointeract:react-accounts-ui` to `std:accounts-ui`.
3. This new version handles social buttons and logging with password or service, `<SocialButtons />` and `<PasswordOrService />` components.
As `accounts-facebook` & `accounts-twitter` are used by `nova:lib`, the `oauthServices` prop passed to them recognize …
=> Show login form instead of new comment form if the user is not logged in

.meteor/versions, package.json, packages/nova-base-components/lib/common/HeadTags.jsx, packages/nova-base-components/lib/common/Header.jsx, packages/nova-base-components/lib/posts/PostPage.jsx, packages/nova-base-components/lib/posts/list/PostListHeader.jsx, packages/nova-base-components/lib/users/UserProfile.jsx, packages/nova-base-components/package.js
Well, seems to work better with dochead than react-helmet @SachaG :)
I wrapped the rendering in a component as recommended by the doc in order to have SSR.
The component accept props, which by default are set to the general information of the Telescope.
I removed the old one from `Header` and placed it in 3 places :
1. `PostPage` container to have access to post props.
2. `PostListHeader` which is displayed on "basic view".
3. `UserProfile` component to have access to a user data.
What do you think of the "placement"?
I'm thinking about using new utils/helpers like `Telescope.utils.getLogoUrl()` instead of `Telescope.utils.getSiteUrl() + Telescope.settings.get("logoUrl"); ` and `Posts.getPostThumbnailUrl()` instead of `post.thumbnailUrl`. It would give a shorthand for access absolute url …
=> HeadTags: dochead instead of react-helmet

packages/nova-base-components/lib/posts/list/PostListHeader.jsx, packages/nova-base-components/lib/posts/list/PostThumbnail.jsx, packages/nova-lib/lib/utils.js, packages/nova-posts/lib/helpers.js
I put HeadTags outside the `post-header-list` div in order to not mess with Flexbox :+1: 
And I created the two helpers `Telescope.utils.getLogoUrl()` which returns the logo url & `Posts.getThumbnailUrl(post)` which returns the thumbnail url.
=> Fix HeadTags <-> Flexbox + add 2 helpers for images

packages/nova-posts/lib/helpers.js
Watch for double slashes in the `thumbnailUrl`, if they exist: use `Telescope.utils.addHttp` to add the missing http:// if needed!
Repairs https://github.com/TelescopeJS/Telescope/pull/1292#issuecomment-208159305
=> Helper: handle thumbnails from embedly, an external website or hosted on the app

packages/nova-base-components/lib/common/HeadTags.jsx, packages/nova-base-components/lib/common/Layout.jsx, packages/nova-base-components/lib/posts/list/PostListHeader.jsx
It will also remove older added tags on the client, so there are no meta tags duplication: see https://github.com/kadirahq/meteor-dochead/#docheadremovedocheadaddedtags.
=> Move head tags to layout

packages/telescope-invites/lib/server/invites.js, packages/telescope-invites/lib/server/templates/emailInvite.handlebars
Current invite link is broken.
Maybe it's because without `siteUrl`. So I just add it at the beginning of the link.
=> Add siteUrl in front of action link. The link is wrong

packages/nova-base-components/lib/common/Layout.jsx, packages/nova-base-components/lib/components.js, packages/nova-base-components/lib/users/UserProfileCheck.jsx, packages/nova-base-styles/lib/stylesheets/_users.scss, packages/nova-base-styles/lib/stylesheets/main.scss, packages/nova-forms/lib/FormComponent.jsx, packages/nova-forms/lib/NovaForm.jsx, packages/nova-lib/lib/settings.js
Reactively show a modal if the profile required fields are not completed. 
The only way to close this modal is to complete the fields or log out with the button provided.
I have used `nova:forms` + `users.edit` method and add a prop `requiredFieldsOnly` to show only `telescope.email`.
=> Completed profile hook

packages/nova-categories/lib/server/load_categories.js
Loading categories inside Meteor.startup() allows inserting categories from settings.json with an extended schema (extended with Categories.addField()).
=> Load categories at startup in load_categories.js

packages/nova-base-components/lib/comments/CommentsItem.jsx, packages/nova-base-styles/lib/stylesheets/_comments.scss, packages/nova-users/lib/permissions.js
This follows the same functionality and style of deleting posts, no use of NovaForm, direct call.
- Add deleteComment function to CommentsItem.jsx
- Add Delete link next to Edit link in CommentsItem.jsx
- Hide reply link if comment.isDeleted
- Add styling for Delete link element in _comments.scss
- Add check for document.isDeleted in Users.can.edit in permissions.js
=> Complete soft delete feature for comments (Revision 2)

packages/nova-base-components/lib/categories/CategoriesList.jsx, packages/nova-base-components/lib/categories/Category.jsx, packages/nova-base-components/lib/posts/PostsEditForm.jsx, packages/nova-base-components/lib/posts/PostsNewButton.jsx, packages/nova-base-components/lib/posts/PostsNewForm.jsx, packages/nova-base-components/lib/users/UsersEdit.jsx, packages/nova-core/lib/components/ModalTrigger.jsx, packages/nova-i18n-en-us/lib/en_US.js
Some stuff I didn't see yesterday night (#1348)
1. Context param for messages.flash on `UsersEdit` https://github.com/TelescopeJS/Telescope/commit/1d047b92e00fcc9e07aa85eaa53299fbe96ebdf5
2. Commenting Messages & ModalTrigger not used anymore https://github.com/TelescopeJS/Telescope/commit/80544da87179e0f3d34c02c69beac97dea450398
3. contextTypes messages on PostsNewButton so the ModalTrigger and PostsNewForm benefit of it! => contextTypes actions, events, messages on ModalTrigger (enable post delete) https://github.com/TelescopeJS/Telescope/commit/cfb720cdcf2dad2495e7c89722a89018db3a8b9a
4. In the row, add a success message on post edit 😌  https://github.com/TelescopeJS/Telescope/commit/6dabd211936a465053f96e9457a28afa65f8318f
So this PR is about context in the most, however we had this …
=> Fixes - Episode II

packages/nova-base-components/lib/common/HeadTags.jsx
Adjusted Open Graph image sharing using custom settings, and verified with Facebook's Open Graph Debugger.
=> Hook up siteImage in settings to the open graph meta tags.

packages/my-custom-package/lib/components/CustomPostsItem.jsx, packages/my-custom-package/lib/intl.js, packages/my-custom-package/lib/modules.js, packages/my-custom-package/lib/routes.jsx, packages/nova-base-components/lib/common/Newsletter.jsx, packages/nova-lib/lib/config.js
I was so into custom packages and understanding react-router + `Telescope.routes` that when I saw that the custom package had used FlowRouter... I couldn't resist 😂 
🎢  Replacement `FlowRouter.route(...)` by `Telescope.routes.add(...)`. 
⌛  Import `moment` where needed.
✉️  `this.renderButton()` wasn't defined anymore (https://github.com/TelescopeJS/Telescope/blob/master/packages/my-custom-package/lib/components/CustomNewsletter.jsx#L24) after the refactoring on the button -> instead of copy/pasting the code of `Telescope.components.NewsletterButton` and its props + context, I recreated the method `.renderButton`.
=> 🐙 Fix custom package

packages/my-custom-package/lib/components/CustomPostsItem.jsx
Completing your last commit on `master`, just a fix on `PostsItem` which didn't render anymore because it couldn't access to its methods `renderCategories` et al. 😅
=> use original PostsItem component

packages/nova-base-components/lib/comments/CommentsItem.jsx, packages/nova-base-components/lib/common/NewsletterButton.jsx, packages/nova-embedly/lib/components/EmbedlyURL.jsx
I saw these 3 components missing the "context refactoring" for Storybook, etc.
Btw, `NovaForms` also depends on explicit `Meteor.call`. As you want it to be used in non-Nova projects, should it use context actions or stay with Meteor.call? I didn't modify it.
=> Decouple components actions from Meteor

packages/nova-base-components/lib/categories/CategoriesNewForm.jsx, packages/nova-base-components/lib/common/HeadTags.jsx, packages/nova-base-components/lib/common/Vote.jsx, packages/nova-base-components/lib/users/UsersAccount.jsx, packages/nova-base-components/lib/users/UsersSingle.jsx, packages/nova-users/lib/server/publications.js
Howdy! 👋 
Here are some stuffs I fixed while playing with the app!
1. 8cb454d : `function()` didn't let `this` `context` go through. (💭  this keyword, context, this context, mmmh. there surely a pun to make but I'm not good english speaker enough)
2. d57cfcf : we couldn't create new category anymore, collection imported in `CategoriesNewForm`
3. c67c04f : Clean a little `HeadTags` and fix a bug: 
=> cleaning: by default the image meta is the logo url defined in settings (force 0). It can also be the siteImage defined in settings (force 1). Or last but not least a props passed to the HeadTags component (force 2). 
=> bug fix: if the image specified is a complete url http, ftp or whatever (contains `//`), don't do anything. Else this would mean it's stored locally, add telescope site url. …
=> Different fixes

package.json, packages/nova-base-components/lib/common/HeadTags.jsx, packages/nova-base-components/package.js, packages/nova-base-routes/lib/routes.jsx
Got it working! 🎸 
You can view the diff by curling my instance & sidebar :
- Nova with helmet: `curl http://meteor.startupfrance.co` -> has meta in the head
- Nova with dochead: `curl http://nova.sidebar.io` -> no meta in the head
ps: I advice to test with `curl` and not fb debugger because I have a nginx issue with the fb debugger on my instance 😓  I do believe that the scraper would see the meta if nginx is well configured (not my case).
=> Meta SSR with react-helmet

packages/nova-base-components/lib/common/HeadTags.jsx
Error on startup was triggered because the app was started without `--settings ...` flag. However it has unveiled, that if someone remove or doesn't define `logoUrl` field from the settings file, Nova can't boot.
*💭  reminder for myself: don't do modification on a var if undefined*
=> don't do modification on a var if undefined => fixes #1375 error

README.md
`nova:categories` was listed twice. Removed second occurrence to maintain alphabetical order.
=> README: Remove duplicate in #optional-packages

packages/nova-posts/lib/helpers.js
`Posts.isApproved` helper return 'false' when admin user is adding new post with the Status = "approved" - the `post.status` is a `String` compared with `Integer` value of `Posts.config.STATUS_APPROVED`.
As a result, the `postedAt` value is not stored in the Posts collection, which leads to ugly error whenever `<FormattedRelative value={post.postedAt}/>` is used, i.e. in the `PostsItem`.
I was able to fix this simply by parsing `post.status` with `parseInt()`.
=> fixed types comparison in Posts.isApproved helper

packages/nova-base-components/lib/common/Newsletter.jsx, packages/nova-base-components/lib/common/NewsletterButton.jsx, packages/nova-forms/lib/NovaForm.jsx, packages/nova-newsletter/lib/components/NewsletterSubscribe.jsx
Hey!
It all started by fixing a bug when editing another user as an admin, if you were to click on the user's newsletter setting, it would un/subscribe yourself.
I needed my `NewsletterSubscribe` to have access to the user document. By passing `getDocument` function in the context, I got errors (`this.props.document is undefined`). 
So I have added a new piece of logic when looping through a fieldSchema : if it's a function (React Component), give it a prop `document`. https://github.com/TelescopeJS/Telescope/commit/91cc0e3f1bdc76fa0cf6fe409cee83377d95f4d5
What do you think of that? I believe it can help to create more flexible/what-ever-you-need components in NovaForms.
(so in this PR, I added this logic and fixed the behavior of the newsletter button)
=> NovaForm: custom control has access to document as a props

packages/_nova-subscribe-to-posts/lib/components/SubscribeButton.jsx, packages/_nova-subscribe-to-posts/lib/custom_fields.js, packages/_nova-subscribe-to-posts/lib/export.js, packages/_nova-subscribe-to-posts/lib/methods.js, packages/_nova-subscribe-to-posts/package.js, packages/my-custom-package/lib/components/CustomPostsItem.jsx
Here is the basic functionality, with one UI component available by import.
```
import { SubscribeButton } from "meteor/subscribe-to-posts";
...
<SubscribeButton post={post} />
```
Like in original code, the `subscribeItem` and `unsubscribeItem` functions are also exported from the package.
Notifications are being send by callback function CommentsNewNotifications from nova-comments/lib/callbacks.js.
ToDo:
- UI component for `user_subscribed_posts` template
- Moving notification from nova-comments/lib/callbacks.js to subscribe-to-posts.
- Cleanup old code
=> Refactored subscribe-to-posts

packages/nova-base-components/lib/components.js, packages/nova-base-components/lib/permissions/CanDo.jsx, packages/nova-base-components/lib/posts/PostsItem.jsx, packages/nova-base-components/lib/posts/PostsNewForm.jsx, packages/nova-base-components/lib/users/UsersEdit.jsx, packages/nova-i18n-en-us/lib/en_US.js
**Goal:** have a generic component to handle permission adapted to the new groups API
**Trigger:** When updating post-by-feed to use the new group API, I realized that I didn't have any check on permission to show or not my components.
**Problem:** Looking at the base components available in `/permissions`, they all do the same kind of things and we repeat the code over and over with just some small variants in 5 components :
- check if the user is logged in or not
- check if the user can perform the action
- display a no permission message
Moreover, in many components, we check permissions like `{Users.canEdit(this.context.currentUser, this.props.post) ? component : ""}` inside render methods.
**Hypothetic solution:** In order to ease the writing of components and handle permissions with …
=> Proposal for a CanDo Higher-Order Component

packages/nova-debug/lib/globals.js
When debugging, I wondered why Posts.find().fetch() returned the same as Users.find().fetch() (with both console.table() on the client and meteor shell)
It's because the imports for the Comments, Users and Posts globals were all importing from nova:posts which exports Posts as default.. so they were equal
=> Corrected imports for debug convenience globals

packages/nova-subscribe/lib/callbacks.js
Added .uniq() for subscribersIdsToNotify in the Categories section to prevent a user from receiving multiple emails if he/she is subscribed to multiple categories.
=> Update subscriberIdsToNotify to send unique emails

packages/nova-base-styles/lib/stylesheets/_posts.scss
Added `flex-wrap: wrap;` to posts-categories for better styling if a user creates a post with too many categories.
Ping @SachaG - to review since @xavcz said you're the best one to review CSS updates.
=> Updated _posts.scss

packages/nova-base-components/lib/components.js, packages/nova-base-components/lib/users/UsersResetPassword.jsx, packages/nova-base-routes/lib/routes.jsx, packages/nova-base-styles/lib/stylesheets/_accounts.scss, packages/nova-users/lib/server.js, packages/nova-users/lib/server/urls.js
This PR is in response to #1480 
The `componentDidMount` method of `UsersResetPassword` was necessary because [the callback for `Accounts.resetPasswordLink`](https://github.com/studiointeract/accounts-ui/blob/87b4469ae50638f9ca6c33de346141b72cfa585f/imports/login_session.js#L77-L83) was not being called. This is due to the fact that `accounts-base` expects the `reset-password` URL to use query fragments (e.g. `/#/reset-password`) in [attemptToMatchHash](https://github.com/meteor/accounts/blob/77b6084c0bd24129c1e7a6d703d9effddaceadcb/packages/accounts-base/url_client.js#L29-L61). Additionally, we modified the resetPassword URL of accounts-base so that it won't generate links with the query fragment as in [this helpful example](http://stackoverflow.com/questions/26603863/override-reset-passw …
=> Add Reset Password Feature

packages/nova-users/lib/avatar.js
two things
1. forgot utilities_avatar
2. change `window.location.origin` to use `Meteor.absoluteUrl` method, for ssr
so if someone set default avatar url to e.g. `image/xxx.jpg`
and server wont alert `'ReferenceError: window is not defined`.
:) 👍
=> default avatar image's URL for ssr

packages/nova-core/lib/modules.js, packages/nova-lib/lib/modules.js, packages/nova-lib/lib/redux.js, packages/nova-routing/lib/store.js
Integrating a REST api into the redux store. The reducers and actions are easy to extend, but I need to add redux-thunk into the middleware stack, hence the PR.
=> Allow redux middleware extensions

packages/nova-forms/package.js, packages/nova-forms/test.js
When trying to use `nova:forms` directly, or any `nova:`* package that depends on `nova:forms`, this issue is encountered.
```
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:
While loading package fourseven:scss@0.9.6:
```
Looking into `fourseven:scss`' [Compatibilty list](https://atmospherejs.com/fourseven/scss) :
```
Meteor Version  Recommended
1.0 - 1.1       3.2.0
1.2 - 1.3.1     3.4.2
1.3.2+          3.8.0
1.4.0           3.8.1
1.4.1+          3.13.0
```
`nova:forms` currently depend on `Meteor 1.3` so `3.8.0` is used.
This appends the `@3.8.0` on `fourseven:scss` and allows the package to be imported.
Package can be validated by running `meteor test-packages nova:forms`.
=> using nova:forms shows issues when being imported

README.md
My editor looks like it did some whitespace clean up. The change is just adding 'deploy' to the ```mup deploy --settings settings.json``` instructions.
=> fixed deployment instructions typo

packages/vulcan-lib/lib/modules/routes.js
I appreciate that you edited the code and point me out that it should throw error. But i think the property of parentRouteName properly should use "[]" and not by "." notation.
I hope we can setup the test and CI for this  as soon as possible so we can guard stuff like this with test.
Still this is related to issue #1606
=> Should call the property of parentRouteName properly

packages/vulcan-base-components/lib/categories/CategoriesList.jsx
The "All Categories" link in the category option used to set the user's query to whatever it already was. With this change, the query is set to a modified copy of the current query that has category filters removed from it.
=> fix bug where All Categories didn't clear the category filter

packages/vulcan-newsletter/lib/server/integrations/mailchimp.js
If the user is already subscribed, the return code is numeric `214`, returned as `code` rather than `message`.
=> use correct code for Mailchimp "already subscribed" state

packages/vulcan-core/lib/modules/default_mutations.js
Transform collection name to lower case as it is done with the other permission strings.
=> Fix remove permission strings

packages/vulcan-accounts/imports/ui/components/LoginForm.jsx
1. remove duplicated ```formatMessage```.
1. ```showMessage``` function pushs converted formatMessage
=> #1658 Fix broken validation error Messages in LoginForm

packages/vulcan-lib/lib/modules/fragments.js
The fragment parser doesn't ignore comments if they include `...`, e.g.
```
fragment CategoriesList on Category {
}
}
```
This PR should fix that.
Also I've modified the regex for parsing GraphQL fragment names to follow the GraphQL spec more exactly.
=> RegisterFragment should respect comments in fragment literals

.meteor/.id
This PR removes the `.meteor/.id` file from the repository.  This is safe to delete because of [this code in Meteor](https://github.com/meteor/meteor/blob/devel/tools/project-context.js#L440-L466).
The `.id` file is meant to be a unique identifier for a project and is generated automatically in new (Meteor) projects.  Since VulcanJS is instead cloned as a boilerplate for a new application, this is less ideal since each project receives the same unique identifier.  The reason this is not ideal is explained within the comment of the removed file:
https://github.com/VulcanJS/Vulcan/blob/e634907530f9d4caf1c40f64b5df9f6c7e7524d4/.meteor/.id
Most importantly, this affects the ability to see any sort of traction on `vulcan:*` packages in Atmosphere since they are aggregated together.  This means …
=> Remove "unique" identifier file.

.meteor/versions
Update the allow/deny package due to security failure reported at: https://blog.meteor.com/meteor-allow-deny-vulnerability-disclosure-baf398f47b25
=> Update allow/deny package

packages/vulcan-forms/lib/components/Flash.jsx, packages/vulcan-forms/lib/components/Form.jsx, packages/vulcan-forms/lib/components/FormComponent.jsx, packages/vulcan-forms/lib/components/FormGroup.jsx, packages/vulcan-forms/lib/components/FormSubmit.jsx, packages/vulcan-forms/lib/modules/components.js
Abstract out bootstrap-specific components in vulcan:forms and register them using registerComponent so that they can be overridden by other gui frameworks like material-ui.
=> Abstract out bootstrap-specific components in vulcan:forms

package.json
bump react-bootstrap -> 0.31.3
=> Bump the react-bootstrap version to get rid of "isMounted is deprecated..." error when opening modals

packages/example-instagram/lib/components/common/Header.jsx, packages/example-membership/lib/components/common/Header.jsx, packages/example-permissions/lib/components/common/Header.jsx
PicsNewForm must be called as a registered component, not as an imported object.
This PR addresses issue #1770.
Three different tutorial example packages are affected.
=> Fix issue #1770

packages/vulcan-users/lib/server/on_create_user.js
I had the necessity to modify the options which are passed to the user schema validation function. That's why I created a synchronous callback for it.
I'm concerned about the name of the hook. Please, give your advice and opinions.
=> Add pre-validate callback on new user creation

package.json
Since we are now using apollo engine, the optics package is no longer required
=> Remove optics-agent from package.json

packages/vulcan-i18n-en-us/lib/en_US.js
Bumped up against this trying to reproduce another bug.
Repro steps:
1) create a user & account & logout
2) create a 2nd user account with the same email but a different login.  Notice that the error is "unknown error" rather than "email already exists"
Turns out it was just a missing i18n string.  Now it says "email already exists".  much more helpful.
=> fix duplicate email returns "unknown error' 

packages/vulcan-forms/lib/components/FormWrapper.jsx, packages/vulcan-routing/lib/client/router.jsx
Fixes a deprecation warning already in place for React17, removes unused childContextTypes from FormWrapper and turn it into a `PureComponent`
=> Fix warnings from React 16 update

jsconfig.json
Once again, now that Vulcan ships with the .vscode folder included, we should take full advantage of it.
The jsconfig adds automatic typing acquisition and enables deeper intellisense.
=> Add VSCode jsconfig

packages/vulcan-core/lib/modules/components/Datatable.jsx
Fix a simple bug in vulcan:admin user list page after a user delete
Repro:
1) go to /admin
2) edit another user, scroll down & click delete, click "ok" to confirm delete
notice the modal stays displayed after the user is successfully deleted
=> fix admin delete user hide bug

packages/vulcan-forms/lib/components/FormWrapper.jsx
In some cases it seems that the loading property is set to true altough the document is already there.
=> Form loading state fix

packages/vulcan-accounts/imports/ui/components/LoginForm.jsx
Currently, the waiting state get's overwritten by the server version, leaving signIn buttons permanently disabled.
=> Set default waiting state to false to avoid SSR override

packages/example-forum/lib/components/common/Newsletter.jsx
Alright, really weird one related to React16 SSR changes.
https://github.com/facebook/react/issues/10591
Basically, React changed it's diff algorithm and now reuses components differently.
So, when the check for showing the newsletter was inside the constructor, instead of generating something along the line of
```html
<div className="newsletter">
{ ... rest of Newsletter code }
</div>
<div>
{ ...content }
</div>
```
the actual result was
```html
<div className="newsletter">
<div>
{ ...content }
</div>
</div>
```
Setting showBanner inside `componentDidMount` fixes that.
=> Fix Newsletter Banner SSR

packages/example-forum/lib/modules/categories/schema.js, packages/example-forum/lib/modules/posts/schema.js, packages/vulcan-lib/lib/modules/collections.js, packages/vulcan-lib/lib/modules/utils.js, packages/vulcan-users/lib/schema.js
`collection.js` is importing `schema.js` for `createCollection` but `schema.js` is importing `collection.js` for varying runtime function definitions resulting in undefined circular load order on files.
=> Fix circular dependencies between schemas and collections

packages/vulcan-core/lib/modules/components/Card.jsx
This make the Card consistent with the Datatable, and allow to hide the `edit` button on cards using the `showEdit` prop.
=> showEdit on Card

packages/vulcan-forms/lib/components/FormComponent.jsx
Most of this has to do with default values: https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-forms/lib/components/FormComponent.jsx#L51
**Checkbox**
- Expects value to be a boolean
- https://github.com/twisty/formsy-react-components/blob/v0.11.1/src/checkbox.js#L21
**CheckboxGroup**
- Expects `value` to be an array
- `formsy-react-components` tries to get `props.value` as an array: https://github.com/twisty/formsy-react-components/blob/v0.11.1/src/checkbox-group.js#L42 which hits the mixin of Formsy: https://github.com/christianalfoni/formsy-react/blob/v0.19.0/src/Mixin.js#L36
**select**
- If the select is of type `multiple`, then the value must be an array
- If the select is NOT `multiple`, then the value must be a scalar
- Therefore, the default value should not be `[]` …
=> Fix React prop warnings for SmartForm

packages/example-forum/lib/components/comments/CommentsItem.jsx
I noticed that the "Edit" and "Reply" cancel methods in CommentsItem.jsx file are not working. For example, when I edit a comment, the "Cancel" option is not working. Likewise with the Reply form.
I confirmed with @justinr1234 for this fix and he said that this is okay because "... SmartForms code already prevents default before calling this callback."
For more details, please see issue reference: #1870
Thanks!
=> Fix the Edit and Reply cancel methods on Comments component in example-forum package

packages/vulcan-debug/lib/modules/callbacks/schema.js, packages/vulcan-email/lib/server/email.js, packages/vulcan-users/lib/avatar.js
- Correct Callbacks schema to ensure compatibility with more recent versions of simpl-schema
- Add option to VulcanEmail.send to not swallow errors
- Only use md5 module of crypto-js to reduce bundle size
=> Various minor bug fixes

package.json, packages/vulcan-accounts/imports/ui/components/LoginFormInner.jsx, packages/vulcan-accounts/imports/ui/components/TrackerComponent.jsx
Fixes #1815 by fixing `tracker-component` (which `LoginFormInner` extends) to no longer use legacy internal React variable and includes TrackerComponent directly in this repo instead of relying on external out-of-date npm package. This fixes `Accounts` buttons appearing to be disabled in production mode because their internal states were not being set properly.
=> Fix TrackerComponent and include in repo to fix Accounts.LoginFormInner

packages/vulcan-debug/lib/components/Components.jsx
Previously, the hocs registered with options (ex: `registerComponent('Foo', FooComponent, [withBar,barOptions])`   ) were not shown in the dashboard from the debug package
=> vulcan:debug : Components Dashboard now shows all hocs

packages/vulcan-lib/lib/modules/utils.js, packages/vulcan-lib/lib/server/main.js, packages/vulcan-lib/lib/server/utils.js
By importing this module on client many other server side only modules end up being bundled to the client and causing some issues with older browsers or [Cordova](https://github.com/VulcanJS/Vulcan/issues/1798), since those modules are not transpiled.
I've just refactored the code to prevent statically importing `sanitizeHtml` on the `modules/utils.js` (that is bundled to the client) and that it is only imported on the server.
=> Remove sanitizeHtml import on client

package.json, packages/vulcan-core/lib/modules/containers/withList.js, packages/vulcan-lib/lib/modules/mongo_redux.js
Basically I found that when having a query selector containing a nested field, mingo would not safe retrieve that value from the documents already present in the local state. That causes the `withList` HOC to break when inserting or editing documents of a type with an active query with that query selector.
More precisely, the change I'm interested in is from [getValue@0.8.1](https://github.com/kofrasa/mingo/blob/bc287e076630a568d92e8e444077172eeab9663f/mingo.js#L2417) to [getValue@2.2.0](https://github.com/kofrasa/mingo/blob/master/lib/internal.js#L140).
As you can see, in 2.2.0 the object is being checked before retrieving the value, so the error is avoided.
1. Create a query that uses a selector with a nested field. For example:
```
{
'someField.someProperty': true,
}
```
2. List …
=> Update mingo to 2.2.0

packages/vulcan-forms/lib/components/Form.jsx
In vulcan-form, in Form.jsx, convertschema was using props.collection instead of this.getCollection() that was creating an error on using collectionName and not collection in Smartform: 
```js
<Components.SmartForm collectionName="myAwesomeCollection"/>
```
This fixes it
=> use this.getCollection() instead of props.collection

packages/vulcan-forms/lib/components/Form.jsx, packages/vulcan-forms/lib/components/FormNested.jsx
Commit 45d508c broke Nestedforms, this should do the trick. 
On Form.jsx, control was replaced by formInput in 45d508c, it should have been input. 
On FormNested, added inputProperties to omitted props passed to FormNestedInput, to avoid overwriting inputProperties of nested fields
=> Fix nested forms after props renaming

packages/vulcan-forms/lib/components/FieldErrors.jsx
Added `error.properties` to follow fae7b5a03282b1e1586f5483a1f2717ed22c8cef .
Kept `error.data` for backwards compatibility, not sure that it's needed. If it is, it might be good to add it to FormErrors too
=> Fix field errors display

packages/vulcan-core/lib/modules/components/Flash.jsx, packages/vulcan-core/lib/modules/containers/withMessages.js
While testing the Posting edit action with latest from `devel` I stumbled on an issue:
```
Form.jsx:517
TypeError: Cannot read property 'id' of undefined
at Flash._this.getProperties (Flash.jsx:33)
at Flash.render (Flash.jsx:44)
at finishClassComponent (modules.js?hash=ffcdd80922dc5d0dd7afe11426e1665a70c9d671:94083)
at updateClassComponent (modules.js?hash=ffcdd80922dc5d0dd7afe11426e1665a70c9d671:94051)
at beginWork (modules.js?hash=ffcdd80922dc5d0dd7afe11426e1665a70c9d671:94676)
at performUnitOfWork (modules.js?hash=ffcdd80922dc5d0dd7afe11426e1665a70c9d671:97508)
at workLoop (modules.js?hash=ffcdd80922dc5d0dd7afe11426e1665a70c9d671:97537)
at renderRoot (modules.js?hash=ffcdd80922dc5d0dd7afe11426e1665a70c9d671:97568)
at performWorkOnRoot …
```
=> Update Flash component and withMessages container

packages/vulcan-forms/lib/components/Form.jsx
This helps with the problem reported in https://github.com/VulcanJS/Vulcan/issues/1958 while using `errorCallback` on `SmartForm` component.
=> Include document prop in mutationErrorCallback method

packages/vulcan-core/lib/modules/containers/withList.js
Follows the recommanded loading from Apollo. See the Apollo docs about [`data.networkstatus`](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-query-data-networkStatus) and [`data.loading`](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-query-data-loading).
One of the issue here was that `loading` did not cover the `refetch` method. The `loading` prop will now be set to `true` whenever some query is on flight, might it be an initial query, a refetch, a loadmore, a poll, or a variable change.
We can still differentiate a `loadmore` state from a `loading` state with the prop `loadmore` which behaviour has not changed.
=> withList Loading prop adjustment

packages/vulcan-lib/lib/modules/collections.js
It would be great to allow mongodb aggregation. I am personally using geoNear for example.
Since version 1.9.0 there is also connectors for mongodb. Maybe it would be better to add it there?
This was my solution for earlier releases.
=> Add MongoDB aggregation to Collections

packages/vulcan-core/lib/modules/containers/withAccess.js
using `withAccess` without setting redirect used to crash the client because there was no test on `redirect`.  New behaviour is: if redirect is not a string then no redirection is done and the component simply is not displayed. If redirect is a string then we push to that direction in the constructor, as it was previously
=> check for redirect before trying to redirect

packages/vulcan-forms/lib/components/FormComponent.jsx
Values are casted to the first field's datatype without taking into account whether the field can have other types or if the actual values matches the first type.
Have multiple data types for one field. As a concrete example, we are working on a files package that defines a field's type like:
```
const FileOrId = SimpleSchema.oneOf(
// accept generic object so the file itself can be send the first time and be saved
// into a files collection
{ type: Object, blackbox: true },
// once the file is saved, the field will the document id as a reference to the document
// in the files collection
String,
);
```
The described problem causes the id to be merged with an object, so if the id is `'1234'` it is converted to `{0: '1', 1: '2', 2: '3', 3: '4'}`.
Cast value only if the current value is …
=> Restrict value altering to allow multiple datatypes in FormComponent

packages/vulcan-forms/lib/components/Form.jsx, packages/vulcan-forms/lib/components/FormComponent.jsx, packages/vulcan-forms/lib/components/FormGroup.jsx, packages/vulcan-forms/lib/components/FormSubmit.jsx, packages/vulcan-forms/lib/components/FormWrapper.jsx, packages/vulcan-i18n-en-us/lib/en_US.js, packages/vulcan-i18n-es-es/lib/es_ES.js, packages/vulcan-i18n-fr-fr/lib/fr_FR.js, packages/vulcan-lib/lib/modules/components.js, packages/vulcan-lib/lib/modules/utils.js, packages/vulcan-ui-bootstrap/lib/components/forms/Checkbox.jsx, packages/vulcan-ui-bootstrap/lib/components/forms/Checkboxgroup.jsx, packages/vulcan-ui-bootstrap/lib/components/forms/Default.jsx, packages/vulcan-ui-bootstrap/lib/components/forms/Email.jsx, packages/vulcan-ui-bootstrap/lib/components/forms/FormComponentInner.jsx, packages/vulcan-ui-bootstrap/lib/components/forms/Number.jsx, packages/vulcan-ui-bootstrap/lib/components/forms/Select.jsx, packages/vulcan-ui-bootstrap/lib/components/forms/SelectMultiple.jsx, packages/vulcan-ui-bootstrap/lib/modules/components.js
- Moved UI portions of FormComponent to FormComponentInner.jsx in vulcan-ui-bootstrap
- Added user alert when the user navigates to another route while there are unsaved changed in the form (disabled by default)
- Added setting forms.warnUnsavedChanges and SmartForm property warnUnsavedChanges to enable user alert
- Added optional Revert button in FormSubmits to allow the user to discard any changes to the form; this is activated by passing a "revertCallback" property to SmartForm (which can be empty: () => {})
- Added two functions that form components can access in the child context: refetchForm() to refetch the document from the database (in case it was updated by a background process), isChanged() to determine if there are any unsaved changes
- For any phrases I have added to en_US.js …
=> Changes to SmartForm behaviour (updated)

packages/vulcan-forms/lib/components/Form.jsx
Adds a `window.onbeforeunload` event to check if the user closes the tab or the browser with unsaved changes on a SmartForm. Only active with `warnUnsavedChanges` prop or setting is `true`
=> Popup warning on page closing for SmartForm unsaved changes

packages/vulcan-forms/lib/components/Form.jsx, packages/vulcan-forms/lib/components/FormComponent.jsx, packages/vulcan-forms/lib/modules/schema_utils.js, packages/vulcan-lib/lib/modules/collections.js
- Added support for fields that have their own subschema
- The code flattens the sub-fields, so the path for `address: { street }` becomes `'address.street'`
- The parent's values are also merged into each child - this way field properties like `editableBy` and `group` can be set on the parent for all children, and can still be overridden by children
- Minor changes were needed in several places to properly support paths, so `currentValues[path]` becomes `get(currentValues, path)`
- In Form.getData(), replaced underscore's `pick` with lodash's `pick` which properly supports paths and returns a new object
- Fixed a bug in collection.getParameters that made it impossible to specify a `limit` with addView or addDefaultView
=> SubSchema Fields

packages/vulcan-lib/lib/modules/components.js
I needed this for:
```
registerComponent('Component', Component, [withStyles, styles, { withTheme: true }], withCurrentUser);
```
where ```withStyles``` takes 2 args.
=> Allow passing multiple args to HOCs

packages/vulcan-users/lib/modules/resolvers.js
The limit is already set in `Users.getParameters`, where it's taken from the setting `maxDocumentsPerRequest`, and was overwritten to be maxed at 100.
=> Remove hardcoded limit to users List resolver

packages/vulcan-lib/lib/server/apollo_server.js
Default behaviour for apollo tracing is now enabled on dev and disabled on prod. To enable on prod, or disable on dev, the private boolean setting `apolloTracing` is available
=> New default for Apollo tracing

packages/vulcan-lib/lib/modules/collections.js
Instead of using `schema` passed when creating the collection, `getParameters` should fetch the schema from `collection.simpleSchema()._schema` to include the fields added with `collection.addField`.
I originally found this when trying to make the `groups` field searchable in the Users collection, with: 
```
Users.addField([
{
fieldName: 'groups',
fieldSchema: {
type: Array,
searchable: true,
},
},
{
fieldName: 'groups.$',
fieldSchema: {
type: String,
},
},
]);
```
I thought a better way to define `collection.getParameters` was outside of `collection.createCollection`, like `collection.addField` is defined ( `Mongo.collection.prototype.addField = function (...) {...}` ), but when trying to rewrite it this way i stumbled on lots of errors, and found out that the committed solution is …
=> collection.getParameters handles schema extension for searchable fields

packages/vulcan-forms/lib/modules/schema_utils.js
I was trying to use SmartForm with a collection only using the new OpenCrud API (`canRead` instead of `insertableBy`, etc) and I found that no fields were showing because the schema arriving to `Form.jsx` did not contain those properties.
=> Pass opencrud field properties to the form

packages/vulcan-lib/lib/modules/fragments.js
Features:
- more fine grained fragment initialization, as `initializeFragements` can now be parametrized with the names of the fragments to initialize (defaults to all non-initialized fragments)
- when retrieving an already registered fragment with `getFragment`, it will be initalized if it isn't
This allows:
1. to use HOCs such as `withList` at compile time. The only requirement now is that all the fragments used are registered.
2. to register fragments in dynamic imports and use them normally
=> Dynamic fragment initalization

packages/vulcan-core/lib/modules/default_mutations.js, packages/vulcan-core/lib/modules/default_resolvers.js, packages/vulcan-lib/lib/modules/collections.js
- allow to specify the `collectionName` for the single-argument API
- merge default options
- register callbacks only for created mutations
=> Minor default resolvers and mutations improvements

packages/vulcan-lib/lib/modules/components.js
@SachaG feel free to improve the warning in order to make it more understandable.
Example of current message:
>Trying to replace non-registered component FormNested. The component is being registered. If you were trying to replace a component defined by another package, make sure that you haven't misspelled the name. Check also if the original component is still being registered or that it hasn't been renamed.
=> Warn when replacing a non-registered component and register it anyway

packages/vulcan-forms/lib/components/Form.jsx
allows for the form fields to be correctly cleared when calling clearForm with `clearCurrentValues == true`
=> [Forms] Add currentDocument to clearForm

packages/vulcan-users/lib/modules/mutations.js
The commit a1a3ffbb8ca33c7af04bdc59e1324104144721ce changed mutation arguments from `{input: {selector, data}}` to `{selector, data}`, which broke the users' package custom mutations.
=> [opencrud] update Users mutations to match {selector, data} args

packages/vulcan-lib/lib/client/render_context.js
I've found that the context is initialized quite early (due to `loginToken` being set by [resetToken](https://github.com/VulcanJS/Vulcan/blob/485f7bad379ba3021278e3cf8de0f2ad23bf6be4/packages/vulcan-lib/lib/client/auth.js#L23)), and usually before many modules have been yet executed. That causes that the `apolloClient` is created before many of the collections are created.
Though in most cases that is not a problem (because the client does not need to know about collections, types, etc.), this causes some problems in more advanced use cases, mainly when using interfaces or unions.
In my particular case, I have a project that relies extensivelly in interfaces. In the hook `apolloclient.init.before` I'm preparing a fragment matcher so the apollo client knows which interfaces exist and which …
=> defer creation of apolloClient until it is first used

packages/vulcan-users/lib/server/callbacks.js
This closes a minor security hole where if you create an account, verify your email address, then change your email address, the new email address is marked as verified (even though you never verified it).
=> When changing email address on an account, mark the new address as unverified

packages/vulcan-lib/lib/server/mutators.js
Simple, just pass collection as a property so callbacks can easilly know to which collection the document being mutated belongs. This is specially useful in the global hooks (such as `*.create.before`) that cannot know it otherwise.
I've only made changes to the new API callbacks.
Since this PR is open, @SachaG do you think we could pass some more info, like `context` for example?
=> Pass collection as property when running new API mutators' callbacks

packages/vulcan-forms/lib/components/Form.jsx
Useful when the callback is meant for side effect management, eg storing some element of the form in the state, and do not modify the document.
=> Allow user to return nothing in submitCallback

.eslintrc, packages/vulcan-core/lib/modules/containers/handleOptions.js, packages/vulcan-core/lib/modules/containers/withCreate.js, packages/vulcan-core/lib/modules/containers/withDelete.js, packages/vulcan-core/lib/modules/containers/withMulti.js, packages/vulcan-core/lib/modules/containers/withSingle.js, packages/vulcan-core/lib/modules/containers/withUpdate.js, packages/vulcan-core/lib/modules/containers/withUpsert.js, packages/vulcan-core/package.js, packages/vulcan-core/test/containers.test.js, packages/vulcan-core/test/index.js
Will fix issues when not specifying a `fragmentName` or `fragment` in `withDelete`, now user only need to pass a `collection` and `collectionName` (default fragment will be used in this case). Also factorized code a bit to get a consistent behavior across hocs. 
I wrote test but could not run them, I have trouble with `@babel/runtime`. Also I did not found out how to mock package methods like `getCollection` during tests.
=> Cleaned up the options management in hocs

packages/vulcan-users/lib/modules/permissions.js
When using the resolver for the resolveAs examples from the documentation:
http://docs.vulcanjs.org/field-resolvers.html
I found that the Users.getViewableFields helper was return array based field names, which obviously are not compatible with the selector/options objects passed through to collection.findOne.
I did a search to see where the function is called in the DEVEL codebase and see that it is used only once.  That being said, others may well be using it and require the array field names, so perhaps might help to create a wrapper function that strips them out to use instead, but for now I figured I would submit this for you.
=> vulcan-users - permissions - filter out array based fields

packages/vulcan-core/lib/modules/containers/withMulti.js, packages/vulcan-core/lib/modules/default_resolvers.js, packages/vulcan-lib/lib/modules/collections.js, packages/vulcan-lib/lib/modules/config.js, packages/vulcan-lib/lib/modules/graphql.js, packages/vulcan-lib/lib/modules/graphql_templates.js
- Added collection.options.singleResolverName and .multiResolverName to stay DRY
- In withMulti, fixed how loadMoreInc passes variables to fetchMore
- Added the "allowNull" option to single resolver to return null instead of throwing a MissingDocumentError
- Added extended SimpleSchema options to support "unique" field property (field can be used as part of a selectorUnique when querying for data)
- When generating schema, populate fields.selector and fields.selectorUnique
=> Minor changes and bug fixes in withMulti, single resolver, schema generation

packages/vulcan-core/lib/modules/containers/withAccess.js
`withAccess` was performing a redundant test: `currentUser && Users.isMemberOf(...)`.
Thus if you added `guests` to the allowed groups, it would fail because `currentUser` is undefined while `Users.isMemberOf()` would have returned true. So I removed the `currentUser` part, since `isMemberOf` will handle unsigned user anyway.
This might sounds weird, because why ass `withAccess` in the first place if we allow `guests`? My use case here is dynamic component generation: you may not know the allowed `groups` in the first place. Sometimes it can contains `guests`, sometimes not, so I prefer to handle both case in an unified way rather than adding a specific test for unsigned users.
Let me know your thoughts on this
=> Allow "guests" in withAccess

packages/vulcan-core/lib/modules/default_resolvers.js, packages/vulcan-lib/lib/modules/utils.js
- Fixed bug in single resolver (slug is undefined)
- Fixed bug in Utils.pluralize (pluralizing words ending in 's', for example address => addresses)
=> Minor bug fixes

packages/vulcan-users/lib/modules/permissions.js
When you run Users.CanCreateField with a function in `canCreate` field prop, it's trying to call a `document` arg that is undefined, because obviously there is no initial document when you try to create a document. So now it's only calling canCreate(user) as defined in the docs. I should have spotted this in #2006, sorry!
=> [BugFix] remove `document` from `canCreateField`

packages/vulcan-email/lib/server/email.js, packages/vulcan-lib/lib/modules/utils.js
`VulcanEmail.send` and `VulcanEmail.buildAndSend` now accepts cc, bcc, and replyTo fields.
`VulcanEmail.buildAndSendHTML` doesn't not support cc, bcc, and replyTo in order to keep it backwards compatible.
=> Added support for cc, bcc, and replyTo fields for email API

packages/vulcan-core/lib/modules/components/App.jsx
See docs: https://github.com/yahoo/react-intl/wiki/Components#dynamic-language-selection
The main problem is that optimization with `shouldComponentUpdate` prevents nested components from updating through context, hence all components below a component that does not rerender won't rerender on locale change.
=> Pass locale as key to IntlProvider to force a rerender on locale change

packages/vulcan-forms/lib/components/Form.jsx
SmartForm.getLabel() now falls back to a "global" namespace when a collection-specific intl string is not found; then it falls back to using no namespace.
This is implemented to reduce duplication of translations, especially for field labels common to multiple collections.
=> SmartForm.getLabel() intl string fallback

packages/vulcan-email/lib/server/email.js
I think it's fine to have reasonable defaults, but the user should be able to override entirely.
The new behavior is as follows:
* email subject is `subject` if set
* otherwise - if no `subject` is set, the email subject becomes `[siteName]`
Tested both scenarios.
=> Email subjects shouldn't be coupled with sitename

packages/vulcan-i18n-fr-fr/lib/fr_FR.js, packages/vulcan-lib/lib/modules/collections.js
When extending a collection's schema with `collection.addField`, and specifically when overwriting an existing field's schema definition, there are some inconsistencies regarding simpl-schema's embedded validation properties : 
See the problem in action by adding this to example-movies : 
```js
import Movies from './movies/collection';
Movies.addField([
{
fieldName: 'name',
fieldSchema: {
max: 5, // ignored
},
},
{
fieldName: 'review',
fieldSchema: {
type: String,
max: 5, // not ignored
},
},
]);
```
Here we add `max` to the two existing fields `name` and `review`, but if you try creating a movie with a name longer than 5 characters it will be validated, the rule `max : 5` is ignored for it. 
This comes from the fact that Vulcan merges the previous schema with the one you extend it with : …
=> Don't merge schema in Vulcan, only do it with SimpleSchema

packages/vulcan-forms/lib/components/Form.jsx, packages/vulcan-forms/lib/components/FormSubmit.jsx, packages/vulcan-forms/lib/components/FormWrapper.jsx
- `submitLabel`, `cancelLabel`, and `revertLabel` now take a node (which is backwards compatible with string) so that you can include a FormattedMessage, an icon, etc.
=> SubmitButtonLabels

packages/vulcan-lib/lib/modules/utils.js, packages/vulcan-lib/lib/server/utils.js, packages/vulcan-users/lib/modules/schema.js
- The slug is updated when the displayname changes
- The `Utils.getUnusedSlug` helper function does not return empty slugs anymore (it's '0' if the `slug` argument is falsy)
=> Users' slug is updated on displayname change

packages/vulcan-forms/lib/components/Form.jsx
Prop `schema` exists in Form's `propTypes` but it wasn't used, the component was always using the schema attached to prop `collection`.
=> SmartForm: use prop `schema`, if given

packages/vulcan-core/lib/modules/components/App.jsx
TLDR: default value in arrow functions that are child to a class breaks MS Edge support 
It seems that babel has an issue with polyfilling arrow functions that have a default value for their arguments.
I found out my site did not support Edge since I updated it to Vulcan 1.12.8.
After a bit of research, I found @Discordius and @jimrandomh from LessWrong had the same issue : https://github.com/LessWrong2/Lesswrong2/issues/783 and found where this was introduced and fixed it in their version of Vulcan : https://github.com/LessWrong2/Vulcan/pull/8
So I just copied what they did, which is delete a default value on an arrow function in the core package: 
```js
getLocale = (truncate = false) => {	 
return truncate ? this.state.locale.slice(0,2) : this.state.locale;	  
};
```
This was introduced …
=> Restore Edge support

packages/vulcan-lib/lib/modules/utils.js, packages/vulcan-lib/lib/server/utils.js
In #2075 I made the mistake of thinking that `onCreate` functions were always exectued in async, which is [not the case for the `Users` collection](https://github.com/VulcanJS/Vulcan/blob/66b1aa467f30a0f3025f022f52bdac5981fbaed7/packages/vulcan-users/lib/server/on_create_user.js#L5). Thus, the slugs would be `[ Object object ]` because `getUnusedSlug` returned a pending promise.
So I reverted to the previous way we did things, using `collection.findOne`. I don't really understand why this is fine in terms of async, but at least it works. I let the version I implemented but it's commented, this way it's not lost and can be reused when we refactor or move out of meteor for example.
=> Revert changes made to getUnusedSlug in #2075

packages/vulcan-forms-tags/lib/components/Tags.jsx
Refactor and fix the `Tags` component:
- fix suggestions (ReactTags accepts {id, text})
- fix updating the parent form (using `props.inputProperties.onChange` instead of `<Input>`), which was not able to save the new state
- lighten state (only `tags` was needed) and streamline callbacks
=> vulcan-form-tags: refactor and fix

packages/vulcan-accounts/imports/emailTemplates.js, packages/vulcan-accounts/main_server.js
Related to #480 
Meteor docs: https://docs.meteor.com/api/passwords.html#Accounts-emailTemplates
Set the email address for:
- resetPassword
- forgotPassword
- verifyEmail
Questions remaining: 
- Is it right to set the `siteName` from the `title` setting, and what is it used for ?
- Can `siteName` and `from` still be overwritten from other packages?
=> set default email and siteName for Accounts related emails

packages/vulcan-core/lib/modules/components/Datatable.jsx
see https://github.com/VulcanJS/Vulcan/issues/2090#issuecomment-433860782
Previously : when you clicked on a sortable column, the results of the fired query would be null, and the next polling would make it right. You had a long time with no results displayed.
Now : The query fired when you click to sort a column returns the right result, with the props updating correctly, so no need to wait for the polling to update the results.
See #2090 for an in-depth explanation
=> Fix datatable bug when sorting a column

packages/vulcan-core/lib/modules/containers/withSingle.js
This adds `refetch` on the props that are passed when using the `withSingle` HOC
=> add refetch to props on withSingle

packages/vulcan-lib/lib/server/apollo_server.js
In particular, the functionality is currently scoped to the maximum request body size (`limit`), which helps avoid errors like `PayloadTooLargeError: request entity too large`
Keys defined here:
https://www.npmjs.com/package/body-parser#bodyparserjsonoptions
=> Allow user to customize apollo json parser options

packages/vulcan-forms/lib/components/Form.jsx
`<Components.SmartForm id="my-id"/>` will now propagate the id to the form element. `<form id="my-id>`
=> Support form id attribute in SmartForm

.prettierrc.js, .vulcan/prettier/index.js, .vulcan/shared/listChangedFiles.js, .vulcan/shared/pathsByLanguageVersion.js, package-lock.json, package.json, packages/vulcan-forms/lib/components/Form.jsx
This commit is to add Prettier to Vulcan's commit pipeline. 
Essentially, before each push, we run a script to see if changed files already have prettier run, if not, we show a message to the user to run ```prettier-all```. We could just skip this check and run ```prettier-all```, which is what I typically do. But I followed what the official react package does and used their own script. 
Also added Husky to do the actually running of the script. Not sure how React team does it, but they have a few script run that does not apply to us. And Husky is what I've used in the past. I am not particularly tied to it, and we could swap this for something else like "git-pre-commit", if a need arises.
We run ```lint``` on pre-commit and ```prettier``` on pre-push.
If this looks good, I can add this …
=> Add Prettier and Husky

packages/vulcan-core/lib/modules/callbacks.js, packages/vulcan-core/lib/modules/components/RouterHook.jsx, packages/vulcan-events/lib/modules/events.js, packages/vulcan-lib/lib/modules/callbacks.js
Pass entire props object to `router.onUpdate` hook.
- `runCallbacksAsync` now can be used on client: it uses promises to defer execution of callbacks instead of `Meteor.defer`
- add `router.onUpdate.async` to avoid breaking changes by changing signature of `router.onUpdate`
Ok, this may seem some trivial changes, but I'll try to explain why I needed them and why I think they can be useful.
By default `router.onUpdate` hook is called everytime the **current Vulcan route** changes. Note the importance of it being the Vulcan route: it won't be called between route changes of the same route definition. For example, route changes between the same route but with different parameters won't trigger the `router.onUpdate`.
To make this to happen is quite straight forward (and didn't need any …
=> Add async hook to RouterHook and provide props as argument

packages/vulcan-core/lib/modules/components/Datatable.jsx
whiteSpace fix for
```
/home/circleci/app/packages/vulcan-core/lib/modules/components/Datatable.jsx
96:54  error  Irregular whitespace not allowed  no-irregular-whitespace
```
=> fixed whitespace to pass linting test

packages/vulcan-forms/lib/components/FormNestedArray.jsx, packages/vulcan-forms/lib/components/FormNestedFoot.jsx
I just saw that we had double the code in the SmartForm for nested array fields. So i'm proposing that we go back to using the previous layout that was better in terms of component separation and customizability.
I'm adding this as a PR for visibility, I think we stopped using FormNestedFoot when @eric-burel made the change for the component API. If this gets no answers in a week I'll consider it ok to merge.
=> Go back to using FormNestedFoot in Nested Array Fields

.vulcan/.gitignore, .vulcan/update_package.js, package.json
As explained in first comment of https://github.com/VulcanJS/Vulcan/issues/2173.
Place Vulcan's `package.json` in `.vulcan/package.json` and run `meteor npm run update-package-json` form your project's folder.
You'll have to manually manage breaking updates (example, from `^2.0.1` to `^3.0.2`).
- makes a backup of the project's `package.json`
- only merges `dependencies`, `devDependencies` and `peerDependencies`
- if full merge is successful, shows a list of updated versions
- will store `vulcanVersion` in `package.json` for future updates
Here's a screenshot of the update process run from `1.12.6` to `1.12.10` in a custom project (result may vary depending on the installed versions):
=> Add script to update package.json dependencies

packages/vulcan-lib/lib/modules/collections.js
If a default view on a collection has an `options.sort` set, Vulcan currently deep-merges this with the `options.sort` on a view, which may also include a sort. Unfortunately, this merge isn't key-order-aware (and is in fact backwards), so this means that a default view can't have a sort specified without overriding the sort on all specific views.
Add a special case for `view.options.sort`, so tahat they don't merge.
=> Default view sort doesn't take precedence over selected view

packages/vulcan-lib/lib/modules/intl.js
Adds a default locale export for intl and default functionality for getString.
Takes the locale from the settings (which in turn defaults to 'en').
=> Add default locale to getString.

packages/vulcan-accounts/imports/ui/components/LoginFormInner.jsx
Adds the current locale to the user profile on signup.
This is useful for localizing the email confirmation.
=> Add locale on signup.

packages/vulcan-lib/lib/modules/intl.js
The previous PR used the default locales only if the chosen locale wasn't defined.
Now the fallback happens on a per-message level.
I've added debug logging for missing locale strings too, as they are hard to spot.
We could modify the `FormattedMessage` component to show a red error message if no string is found...
=> Add debug messages for missing strings and default locale on per-message level.

packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSwitch.jsx
After testing the Switch component for Material UI I detected that doesn't change the state.
We detected that the issue was related to the parameters sent to the onChange function.
this small change do the magic.
=> Re-enable Switch component for Material UI

packages/vulcan-ui-material/lib/components/forms/base-controls/MuiCheckboxGroup.jsx
After testing the CheckboxGroup component for Material UI I detected that doesn't change the state.
We detected that the issue was related to the parameters sent to the onChange function.
this small change does the magic.
=> Re-enable CheckboxGroup component for Material UI 

packages/vulcan-users/lib/server/callbacks.js
Currently, when a user sets their "bio" to an empty string, the denormalized `htmlBio` field doesn't get updated, because empty-string is falsy. Fix that.
=> Fix denormalization when bio set to empty

.meteor/versions, packages/vulcan-core/lib/server/start.js, packages/vulcan-lib/package.js, packages/vulcan-newsletter/README.md, packages/vulcan-newsletter/lib/server/cron.js, packages/vulcan-newsletter/lib/server/newsletters.js, packages/vulcan-ui-material/.versions
The `synced-cron` package was stuck on an old version (1.1.0, late 2014) because when it changed maintainers, it also changed package name. The newer versions include some somewhat important bug fixes; so, upgrade.
This is a breaking change! If you're using Vulcan, you will need to replace imports of `percolatestudio:synced-cron` with imports of `littledata:synced-cron`.
=> Update synced-cron across a maintainer change

packages/vulcan-accounts/imports/ui/components/EnrollAccount.jsx, packages/vulcan-accounts/imports/ui/components/ResetPassword.jsx
The password change message was "Password changed.!" with irregular punctuation (`.!`). This is because the i18n messages ended with a period, while the component was adding an exclamation point. Take out the exclamation point, so that it's "Password changed.".
=> Fix punctuation of password-change message

packages/vulcan-forms/lib/components/Form.jsx
Forms have an `addField` prop, which can be used to override the defaults of which fields are visible in a form. We use this in combination with a custom submit button to make comment boxes show for logged out users (who don't have write/create access to the relevant fields). But it turns out that if you have a nested schema, it tries to add the extra fields into the subschema, not just the root schema, resulting in a crash.
=> Fix a crash when using addFields together with a recursive schema

package-lock.json, package.json, packages/vulcan-core/test/containers.test.js, packages/vulcan-lib/lib/modules/callbacks.js, packages/vulcan-lib/lib/modules/collections.js, packages/vulcan-lib/lib/modules/graphql/graphql.js, packages/vulcan-lib/lib/modules/graphql/index.js, packages/vulcan-lib/lib/modules/graphql/schemaFields.js, packages/vulcan-lib/lib/modules/graphql/typedefs.js, packages/vulcan-lib/lib/modules/index.js, packages/vulcan-lib/lib/server/apollo-server/apollo_server.js, packages/vulcan-lib/lib/server/apollo-server/context.js, packages/vulcan-lib/lib/server/apollo-server/initGraphQL.js, packages/vulcan-lib/lib/server/apollo-ssr/apolloClient.js, packages/vulcan-lib/lib/server/site.js, packages/vulcan-lib/test/server/graphql.test.js, packages/vulcan-lib/test/server/index.js, packages/vulcan-lib/test/server/mutators.test.js, packages/vulcan-test/lib/server/isoCreateCollection.js, packages/vulcan-test/lib/server/main.js, packages/vulcan-test/package.js
Hi,
I've added a few tests and cleaned up GraphQL code generation. I've gathered a few remarks:
- `after` callbacks of the createMutation does not seem to be respected. This line `document = await Connectors.get(collection, document._id);` basically overrides them by fetching the document from the database. It thus ignore previously run callbacks. It should be placed before `after` callback are run, while now it is placed after.
- I splitted the code of the `graphql` generation, but actual modifications are minors. I just needed to be able to reset the state in order to write tests and I needed to refactor things a little to wrap my head around existing code.
- I could not drop a collection automatically. I tried to write an `isoCreateCollection` helpers for tests that deletes a …
=> Additional tests

packages/vulcan-lib/lib/modules/settings.js
`getSetting` was checking its `settingDefault` parameter for truthiness, rather than for presence. This meant that if you pass a settingDefault of false, and the setting isn't defined and doesn't have a registered default, then instead of getting false you'll get undefined. This caused some subtle breakage in LessWrong when the result of getSetting was then used in a mongodb selector, where undefined and false have very different meanings.
=> Fix a falsy-vs-undefined bug in getSetting

packages/vulcan-ui-material/lib/components/core/Datatable.jsx
intl.formatMessage returns undefined and not the defaultMessage if id is not found then resulting in empty headers.
=> ui-material: updated Datatable.jsx - header fix

packages/vulcan-accounts/imports/ui/components/LoginFormInner.jsx
This will respect defaultValue on extraFields in AccountsLoginForm, even with no onChange event triggered, and will allow hidden fields when needed
Should also fix #2258
=> add consideration to default values on accounts extra fields

.babelrc, .meteor/versions, .meteorignore, .storybook/addons.js, .storybook/config.js, .storybook/decorators/BootstrapDecorator.js, .storybook/decorators/MaterialUIDecorator.js, .storybook/helpers.js, .storybook/loaders/starter-example-loader.js, .storybook/mocks/Meteor.js, .storybook/mocks/Mongo.js, .storybook/mocks/Vulcan.js, .storybook/mocks/meteor-apollo.js, .storybook/mocks/vulcan-email.js, .storybook/webpack.config.js, package-lock.json, package.json, packages/vulcan-forms/lib/components/Form.jsx, packages/vulcan-forms/lib/components/FormComponent.jsx, packages/vulcan-forms/lib/components/FormError.jsx, packages/vulcan-forms/lib/components/FormGroup.jsx, packages/vulcan-forms/lib/components/FormNestedArray.jsx, packages/vulcan-forms/lib/components/FormNestedObject.jsx, packages/vulcan-lib/lib/modules/intl.js, stories/form.stories.js, stories/vulcan.stories.js
I got rid of the FormMessage regression regarding the defaultMessage prop. I also made it possible to return global form error without tying them to a specific field name.
And more importantly...I've added Storybook to the core. Bootstrap is used as the default UI lib. It works fine, except that you have to rerun `populateComponent` in each file after you imported your component, in order to have a correctly defined `Components`. 
We would have to find a way to run `populateComponent` after story are imported but before they are run to improve this, a bit like `Meteor.startup` does.
=> Add storybook, few fixes on FormError + Intl messages

.storybook/config.js, packages/vulcan-lib/lib/modules/ui_utils.js, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiCheckboxGroup.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiRadioGroup.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSuggest.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSwitch.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Checkbox.jsx, packages/vulcan-ui-material/lib/components/forms/controls/CheckboxGroup.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Date.jsx, packages/vulcan-ui-material/lib/components/forms/controls/DateTime.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Default.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Email.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Number.jsx, packages/vulcan-ui-material/lib/components/forms/controls/PostalCode.jsx, packages/vulcan-ui-material/lib/components/forms/controls/RadioGroup.jsx, packages/vulcan-ui-material/lib/components/forms/controls/RegionSelect.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Select.jsx, packages/vulcan-ui-material/lib/components/forms/controls/SelectMultiple.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Textarea.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Time.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Url.jsx
Hi,
As suggested by @justinr1234 we may have regression in Material UI forms in the current implementation. `inputProperties` are taken into account, but they overshadow props specific to Material UI inputs.
I tried to provide a solution here, @justinr1234 what's your opinon on this?
I've had some troubles with `inputProps` prop of Material UI, because it seems to create unexpected behaviour. Eg if `inputProps` is defined, then the top level `onChange` seems to be ignored.
=> [WIP] fix MUI inputProperties handling

packages/vulcan-ui-material/lib/components/forms/FormComponentInner.jsx
When passing a custom Input for an array in a schema it crashes because it calls an inexisting element FormNested. I just erased this if et it will just use the FormInput
=> FormComponentInner calling an inexisting element (FormNested) 

packages/vulcan-lib/lib/modules/ui_utils.js
When the schema defines inputProperties.disabled as a function, it's already evaluated to a boolean by this point. However props.inputProperties still has it as a function. Having ...props.inputProperties at the end of the spread overwrites the boolean with the function, resulting in an error.
=> inputProperties function parameters bug

packages/vulcan-forms/lib/components/Form.jsx, packages/vulcan-forms/lib/components/FormGroup.jsx
The way a field's group parameters are passed down to FormGroup does not allow for optional group parameters, such as "startCollapsed".
=> FormGroupOptionalParameters

packages/vulcan-lib/lib/modules/components.js
Returns true if a component with the given name has been registered with registerComponent(name, component, ...hocs).
=> vulcan-lib: New function: componentExists(name)

packages/vulcan-lib/lib/modules/components.js
instantiateComponent() can now be passed a react element in addition to a component and a component name
=> instantiateComponent with React element

packages/vulcan-users/lib/modules/mutations.js, packages/vulcan-users/lib/server/on_create_user.js
Change the signature of the user.create.async callback to be more consistent with other create callbacks
=> user.create.async callback

packages/vulcan-forms/lib/components/FormGroup.jsx
`adminsOnly` is a new option for form groups. This allows you to put form fields that members canRead, but you only want admins to see in the form
=> FormGroupAdminsOnlyOption

packages/vulcan-lib/lib/server/inject_data.js
Fixed bug: EJSON.stringify() will throw a stack overflow error when attempting to stringify an object with circular references
=> EJSONStackOverflow

packages/vulcan-lib/lib/modules/utils.js, packages/vulcan-lib/test/index.js, packages/vulcan-lib/test/utils.test.js
`Utils.getUnusedSlug()` creates a problem when a document is renamed, but its slug remains the same. For example, if 'RENAMED NAME' is changed to 'Renamed name'; the slug would change from `renamed-name` to `renamed-name-1`. To resolve this, pass the document's _id as the 3rd parameter to `getUnusedSlug`. Unit tests included.
=> Fix bug in Utils.getUnusedSlug()

packages/vulcan-lib/lib/modules/config.js, packages/vulcan-lib/lib/modules/graphql/collection.js, packages/vulcan-lib/lib/modules/graphql/graphql.js, packages/vulcan-lib/lib/modules/graphql/resolvers.js, packages/vulcan-lib/lib/modules/graphql/schemaFields.js, packages/vulcan-lib/lib/modules/graphql_templates.js, packages/vulcan-lib/lib/server/apollo-server/initGraphQL.js, packages/vulcan-users/lib/modules/permissions.js, packages/vulcan-users/lib/modules/schema.js
Hi all,
This is a draft of the way we should handle nested types IMO. 
Here is a recap of how it works, as said in #2323 : 
Every time we create a collection with a schema, it registers the graphql schema through a function called `addTypeAndResolver` (name to change maybe). This function creates the type definition, input types and resolvers for the **flat** type. Nested types have to be registered directly through this function, and can be referenced thanks to another function `getType` (name to change because too generic). Also, each field resolver checks the `canRead` to make sure the field can be read by the user. One thing to get though, is that the `canRead` is tied to the type, so if you reuse the type at two places, then it will have the same schema.
You can see an example in …
=> Handle Nested types the graphql way

packages/vulcan-core/lib/modules/components/App.jsx, packages/vulcan-core/lib/modules/components/RouterHook.jsx, packages/vulcan-events-segment/lib/client/segment-client.js, packages/vulcan-events-segment/lib/server/segment-server.js, packages/vulcan-events/lib/modules/events.js, packages/vulcan-lib/lib/modules/utils.js
Re-enable RouterHook component in App.jsx so that page view events are sent to analytics.
* Moved `RouterHook` component from `App` (where it was commented out anyway) to `RouteWithLayout`
* Fixed bug: changed `router.onUpdate.async` to `router.onupdate.async`
* In `vulcan:events-segment` upgraded the Segment analytics snippet to version '4.1.0'
* Fixed bug: `segmentIdentifyServer()` would identify the same user repeatedly (several times a minute)
* Unrelated: Added JSDoc to `Utils.getUnusedSlug()` and `Utils.getUnusedSlugByCollectionName`
=> Re-enable RouterHook component so that pageview events are sent to analytics

packages/vulcan-ui-material/history.md, packages/vulcan-ui-material/lib/components/forms/base-controls/StartAdornment.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/mixins/component.jsx, packages/vulcan-ui-material/package.js, packages/vulcan-ui-material/readme.md
* Url and email inputs are now adorned with an icon button link - unless you pass `hideLink: true` in inputProperties
* Brought version up to 1.13.2 including history and readme
=> MaterialUiStartAdornment

packages/vulcan-core/lib/modules/components/Card.jsx
• Enable the Components.Card component to additionally support the props supported by the Components.SmartForm component
• Is is now possible to hide schema fields displayed on an editable Card component on the form displayed when the Edit button is clicked
• It is possible to elect to not show schema fields that ordinarily would be shown by default on a SmartForm using the hideFields prop. This same feature was not available on the Card component and more specifically to be able to hide schema fields on the Card edit form. The edit form uses the SmartForm so the solution was minimal and required simply passing the applicable SmartForm props specified on the Card component down the child component hierarchy to the SmartForm called to enable Card editing.
=> Ensure  props that can be applied to the SmartForm component  are propagated when said props are specified on the Card component.

packages/vulcan-ui-material/readme.md
When you add react-jss without a version it will install the newly released version 10 (released 5 days ago)
You will get an error "Module not found: Can't resolve 'react-jss/lib/JssProvider"
There is already in issue in material-ui 
https://github.com/mui-org/material-ui/issues/13146
It solved the issue for me with this comment
https://github.com/mui-org/material-ui/issues/13146#issuecomment-534532789
I also tried to install it with @9.0.0 but npm didnt find any matching version. With the last version of 8.1.0 it works great
=> Material-UI - README Installation - Set Version of react-jss

packages/vulcan-forms/lib/components/Form.jsx, packages/vulcan-forms/lib/components/FormGroup.jsx, packages/vulcan-ui-bootstrap/lib/components/forms/FormGroupDefault.jsx, packages/vulcan-ui-bootstrap/lib/modules/components.js, packages/vulcan-ui-bootstrap/lib/stylesheets/style.scss, packages/vulcan-ui-material/lib/components/forms/FormGroupDefault.jsx, packages/vulcan-ui-material/lib/components/forms/FormGroupLine.jsx, packages/vulcan-ui-material/lib/components/forms/FormGroupNone.jsx
* Functions passed as values in `inputProperties` are now called with an additional parameter: `document`
* `FormGroup` now accepts a `hidden` property, which can also be a function
* Split bootstrap-specific code out to `FormGroupDefault`
* Implemented `group.hidden` prop in `vulcan:ui-bootstrap` and `vulcan:ui-material`
=> FormGroupHiddenProp

packages/vulcan-core/lib/client/start.jsx, packages/vulcan-core/lib/modules/callbacks.js, packages/vulcan-core/lib/modules/index.js, packages/vulcan-lib/lib/modules/routes.js, packages/vulcan-lib/lib/server/apollo-ssr/enableSSR.js, packages/vulcan-lib/test/index.js, packages/vulcan-lib/test/routes.test.js
I've added a `startup.before` callback ran before routes and components are populated.
This allow to call functions during startup, but before Routes and Components are fully populated.
First use case is the Backoffice creation: https://github.com/VulcanJS/Vulcan/issues/2176
You need to wait for startup because otherwise Collections may not be correctly defined, but you also need to call it before Routes are fully populated in order to add a route for each collection.
Note that this call back won't be called before all `Meteor.startup`, but before the ones in `start.jsx` and SSR rendering.  Maybe we can find more appropriate names or even add additionnal callbacks like `render.before` or `populateRoutes.before` etc.
Closes https://github.com/VulcanJS/Vulcan/issues/2404
=> populate.before callback

packages/vulcan-ui-material/lib/components/bonus/TooltipIconButton.jsx
Before, the aria-label was the title variable, which could be empty if an intl id was passed. Using the titleText which gets or the title or the intl id text, we can guarantee an useful aria-label
=> TooltipIconButton arialabel titletext bugfix

packages/vulcan-lib/lib/server/utils.js, packages/vulcan-users/lib/modules/helpers.js
Issue: Bug Fix
Condition '!operation' is always false at this point because it is redundant. 
Solution:
Removed  redundant operation check as it's checked in previous line
packages/vulcan-lib/lib/server/utils.js
CONSTANT_CONDITION
throwError({ id: 'app.document_not_found', data: { documentId, operationName } });
}
if (!operation(user, checkedObject, context)) {
throwError({ id: 'app.operation_not_allowed', data: { documentId, operationName }
=> Condition '!operation' is always false at this point because it is redundant. 

README.md
Looks like in A records for telescopeapp.org didn't set properly for redirect from http://telescopeapp.org to http://www.telescopeapp.org (which is the only URL for which server will send you page). So, basically, right now when you follow link telescope home page will not be opened, but 404 error will be received instead (at least, this is Chrome current behavior when you follow link) because there is http before link, another solution, instead of directly putting of "www" will be removal of protocol from link
=> Incorrect link to telescopeapp.org

README.md
For some reason, links led just to repo, instead of files relevant for branch.
=> Fixed links to changelog and migration documentation to

packages/vulcan-core/lib/modules/containers/cacheUpdate.js, packages/vulcan-core/test/containers/mutations.test.js
Example if we have in cache
myCustomQuery({limit:8}) //The one I want
myCustomQuery //I know I don't want this because causes an error in the line JSON.parse 
myCustomQueryFoo({limit:8}) //I don't want it
The test tries this three cases and asks to return just one, the first. If in the future we would want to manage the second case too.
=> prevent cacheUpdate from returning variables of a query similar name 

packages/vulcan-core/test/containers/mutations.test.js
Split of the test to two cases : 
- Queries starting with the same string (myCustomQuery({... and myCustomQuery2({...)
- Ignore zero variable queries 'myCustomQuery'
=> split getVariablesListFromCache test in two

packages/vulcan-core/lib/modules/components/Datatable/DatatableContents.jsx
If the collection exists, but is empty, and no columns are specified, the code would fail as results[0] would be undefined.
=> Check if results is non-emtpy, not just present

packages/vulcan-core/test/containers/mutations.test.js
With this PR, in addition to test that the correct number of queries are parsed, it is assured that the correct one is parsed and that the variables are correctly read.
=> testing getVariablesListFromCache, verifiying right variables are returned

packages/vulcan-ui-material/lib/components/ui/ModalTrigger.jsx
The lack of a preventDefault is blocking the `a tag` or the Link from working.
=> add preventDefault to ui-material ModalTrigger

packages/vulcan-lib/lib/modules/graphql_templates/mutations.js
Before this patch, the new single variable `input` API was causing the following error when used with `useUpdate2`. 
```
[GraphQL error]: Message: Variable "$data" of required type "UpdateGroupDataInput!" was not provided., Location: line 1, col 85, Path: undefined
```
This patch fixes the issue for update & upsert.
=> Set non-null to false for data input type on update/upsert

packages/vulcan-lib/lib/modules/mongoParams.js
Deletes the `async` on the `forEach` callback as we're not `await`ing anything in there.
(it looks like this async was previously needed as there was an await on the customFilter call but that seems to be gone now)
=> remove async to fix issue in mongoParams.js filterFunction

packages/vulcan-core/lib/modules/containers/multi2.js
Fixes two issues I'm running into using `withMulti2({input: ...})`:
1. The limit that is provided as part of the input (`options.input.limit`) was not being used, instead the limit was always `defaultInput.limit`.
This is because `options.input.limit` is not one of the values that the function `initialPaginationInput` looks for, so it ends up going with the default for paginationInput.
This will now check for a provided `options.input.limit`.
2. `loadMoreInc` was returning duplicate values.
This seems to be because `fetchMore` changes the input variable of the original query to use terms: `variables: { input: { terms: newTerms } }`.
Instead of overriding the input like this, I've changed loadMoreInc to accept an input (which user can set as desired, including offset) or default to an …
=> check options.input.limit and loadMoreInc accepts input

packages/vulcan-forms/lib/modules/schema_utils.js, packages/vulcan-lib/lib/modules/config.js
These edits allow you to use `itemProperties` in a schema.js file, like:
```...
input: 'textarea',
itemProperties: {
layout: 'inputOnly'
},
...
```
See Slack discussion at https://vulcanjs.slack.com/archives/C02L990AF/p1574895832425900 thru https://vulcanjs.slack.com/archives/C02L990AF/p1574900591428300
=> Add support for `itemProperties` in schemas

packages/vulcan-lib/lib/server/default_mutations.js
Before if a user owned a document and belonged to an authorized group but it wasn't allowed to owners to modify, the user would not be able to edit.
=> fix default_mutations check if user owns and belongs to authorised group

packages/vulcan-users/lib/server/on_create_user.js
When username is non-optional, the current code throws a validation error. 
If this function is going to delete username from options, then username should be omitted from the schema validation.
=> Omit username from schema validation after deleting it from options

packages/vulcan-lib/lib/server/debug.js
**Context:** 
This function is aimed at enabling generation of typescript definitions for the default queries provided by Vulcan. Tools like [apollo codegen:generate](https://github.com/apollographql/apollo-tooling) generate typescript definitions when provided with a schema and queries/fragments. These definitions can be used to strongly type `useQuery`, `useMulti2`, and `useSingle2`. We're leveraging this currently at TradeWing and it really improves the developer experience. However, apollo codegen:generate needs a file that specifies the queries in order to generate the definitions.
**Changes:** 
* Adds an optional fileName argument to Vulcan.getGraphQLSchema - this helps with the auxiliary typescript generation scripts.
* Adds the Vulcan.generateGraphQLQueries function - this writes …
=> Add Vulcan.generateGraphQLQueries to debug.js

MIGRATING.md, packages/vulcan-lib/lib/modules/schema_utils.js, packages/vulcan-lib/lib/modules/simpleSchema_utils.js, packages/vulcan-lib/lib/modules/validation.js, packages/vulcan-lib/lib/server/graphql/schemaFields.js, packages/vulcan-lib/test/documentValidation.test.js, packages/vulcan-lib/test/index.js, packages/vulcan-users/lib/modules/permissions.js, packages/vulcan-users/test/permissions.test.js
Behaviour before PR:
```
const fooSchema = {
nested: {
type: new SimpleSchema({
foo: {
type: String,
canCreate:["admins"] // this is ignored => members can actually create foo
})
canCreate: ["members"]   // this is validated, only members can create the "nested" object
}
```
The obvious issue is that nested permissions are ignored. This is not a bad beahviour per se, but it could confuse users.
After the PR:
```
const fooSchema = {
nested: {
type: new SimpleSchema({
foo: {
optional: true,
type: String,
canCreate:["admins"] // this is also taken into account
})
canCreate: ["members"]   // you still need this
}
```
So "members" could create an empty "nested", but not "nested.foo".
This is better. 
However, if you remove the `canCreate: ["members"']` at the root of the object, the whole …
=> Field level permissions validation take nested objects into account (read, create, update)

packages/vulcan-core/lib/modules/containers/multi2.js, packages/vulcan-core/lib/modules/containers/single2.js, packages/vulcan-lib/lib/modules/simpleSchema_utils.js, packages/vulcan-lib/lib/modules/utils.js, packages/vulcan-lib/lib/server/graphql/schemaFields.js, packages/vulcan-lib/test/utils.test.js
Update Utils.convertDates, that transform date isostring to native `Date` object on the client (scalar handles this server side but not client side).
Need https://github.com/VulcanJS/Vulcan/pull/2451 to be merged beforehand, as it includes a `forEachDocumentField` helper to loop over nested fields.
=> Rewrite client side date converter to handle nesting

packages/vulcan-core/lib/modules/containers/create2.js
This allows the client to access the created document without providing the resolverName, similar to the logic in useMulti2 and useSingle2.
=> Add buildResult functionality to useCreate2 to directly access created document

packages/vulcan-forms/lib/components/FormComponent.jsx, packages/vulcan-ui-bootstrap/lib/components/forms/Password.jsx, packages/vulcan-ui-bootstrap/lib/modules/components.js, packages/vulcan-ui-material/lib/components/forms/controls/Password.jsx, packages/vulcan-ui-material/lib/components/index.js, stories/form/formControls.stories.js
Add a password component for both bootstrap and materialize.
Based on the Default (text) input, I just added a `type='password'`.
=> Add a password component

packages/vulcan-lib/lib/server/query.js
This was causing a TypeError in vulcan-files because the file collection was not being added to the context that is passed to the resolvers in that package when querying with `runGraphQL`
=> Add GraphQLSchema.context to context in runGraphQL

stories/datatable.stories.js
Pass default propos to the datatable-loading component to prevent component crash.
Closes #2481
=> Fix datatable-loading crash in the storybook

packages/vulcan-lib/lib/server/apollo-ssr/components/Head.jsx
This is done to avoid two generated opening head tags. The dynamicHead
passed as a paramter to the headTemplate already contains the opening
tag.
Related issue: VulcanJS/Vulcan#2443
=> Remove hardcoded head tag in template-web.browser

packages/vulcan-lib/lib/server/apollo-server/context.js
I've added `context.req.connection.remoteAdress`, which usually includes the user IP.
I have some question though: is it a good practice to pass the full HTTP request to resolver context? That would solves some issues, as the user can freely access HTTP request, eg to get user ip or similar low level features.
But at which point the `context` becomes bloated?
Also we lack a pattern to enhance the GraphQL context, maybe an additional callback would be appropriate if many users want to enhance it.
Closes #1819
=> add connection remoteAdress in context

packages/vulcan-lib/lib/modules/collections.js
The current implementation fails to map `Foo!` to the foo collection.
=> Remove ! when parsing typename

packages/vulcan-lib/lib/modules/collections.js
The current implementation is buggy when Array.isArray(a) !== Array.isArray(b)
This can be the case for permissions `['members']` vs.  `() => ....` for example
=> fix bugs in extendCollection (#16)

packages/vulcan-lib/lib/modules/validation.js
Fixes a bug I ran into when `isNested === false` and `mode === create` and `fieldSchema.canUpdate === undefined`. Surprisingly, the `if` on this line was evaluating to true leading to the early return.
Adding the parentheses fixes the operator precedence issue on this line and runs as intended. Verified that it fixes the issue we were seeing.
=> fix field permission validation bug

packages/vulcan-accounts/imports/ui/components/Button.jsx, packages/vulcan-core/lib/modules/components/Card/Card.jsx, packages/vulcan-core/lib/modules/components/Datatable/Datatable.jsx, packages/vulcan-forms/lib/components/Form.jsx
Classnames of wrapper component such as datatable and forms are now semantized. (In particular buttons and links to sign in and register)
It's possible to access each part of the component with a unique class or id name.
This PR is linked with this one: https://github.com/VulcanJS/Vulcan-Starter/pull/156
Closes #2423
=> Semantized classname

packages/vulcan-lib/lib/modules/schema_utils.js
Avoid failing when a field is present in a JSON document but is not declared in the schema.
Theoretically this is not a valid pattern, however as `forEachDocumentField` is a generic helper we can reasonnably expect it not to fail on invalid documents and let the user decide what to do with missing fieldSchema instead 
@kevinashworth for feedback
=> Prevent calling forEachDocumentField on fields without a schema

packages/vulcan-forms/lib/components/FormGroup.jsx
Move `itemProperties` above `field` inside `FormComponents.FormComponent`
It seems that destructing `{...field}` effectively removes itemProperties from getting sent to FormComponent because `{...field}` includes an itemProperties
So for me, this change gets `itemProperties: { layout: 'inputOnly' }` working again in `schema.js` use
=> Allow itemProperties to be passed on to FormComponent

packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSelect.jsx
official selectmulti example:
https://codesandbox.io/s/hzojf
the special handling of a change is relevant only while `native` and `multiple` are selected
=> fix material ui seletmultiple

packages/vulcan-ui-material/lib/components/bonus/TooltipButton.jsx
Hi ! 
In the **TootltipButton**, the **title** is used as the **aria-label** for different material ui components.
I think we should use the **titleText**, which is more resistant than the **title**.
Have a good day
=> change tooltip aria-label

packages/vulcan-core/lib/modules/containers/update2.js
This needs to be properly tested before getting merged. Based on Unit
Tests it does not break anyting.
When building the demo application for the new datatable with @loustak,
we will make sure to try this commit out.
=> Use multiQueryUpdater in update2 to properly sort/filter

packages/vulcan-lib/lib/server/utils.js
The `strike` tag is no longer a valid HTML tag. See https://www.w3schools.com/tags/tag_strike.asp
Two very similar tags are its replacement, `s` and `del` -- and `del` has a corresponding `ins` tag. See https://www.w3schools.com/tags/tag_del.asp and https://www.w3schools.com/tags/tag_s.asp
So take out the old `strike` tag and add in `s`, `del` and `ins`.
=> Update to current valid strikethrough tags

packages/vulcan-forms/lib/components/FormComponentLoader.jsx
This structure is necessary for my app to not crash when it loads a SmartForm. 
It is also in keeping with the code in Apollo example. See https://www.apollographql.com/docs/react/api/react-hooks/#example
=> Don't run `options` function until `loading` is false, and `data` is populated

packages/vulcan-lib/lib/server/mutators.js
When using onEdit we should get as args : cf. https://github.com/VulcanJS/Vulcan/blob/51acfa7ffcec844cab882f661ca314df19f56fa4/packages/vulcan-lib/lib/server/mutators.js#L193 
- modifier
- oldDocument
- currentUser
- document
Nevertheless, in the current version we get document twice which prevents us from verifying oldDocument properties. I think at some commit document became oldDocument and newDocument became document.
=> Enable OpenCRUD backwards compatibility

package.json, packages/vulcan-accounts/imports/useMeteorLogout.js, packages/vulcan-accounts/imports/useSignout.js, packages/vulcan-accounts/main_client.js, packages/vulcan-accounts/main_server.js
Also added `@apollo/react-hooks` as a dependency since it's also used elsewhere in the codebase.
The hook simply takes a callback and does the same as the already existing logout function from `LoginFormInner` from the same package
=> Add useSignout hook to the accounts package

package.json, packages/vulcan-core/lib/modules/components/HeadTags.jsx
The NFL has released version 6.0.0 of react-helmet. It has one breaking change re named import/export: https://github.com/nfl/react-helmet/wiki/Upgrade-from-5.x.x----6.x.x-beta
=> feature/update react-helmet

packages/vulcan-forms/lib/components/FormComponent.jsx, packages/vulcan-forms/lib/components/FormGroup.jsx
Reverse commit 594bf423bc86aa83061b53866f6fcefa6415be03
SmartForm changes from a week ago cause an error — cannot create or update nested inputs, like those in the Addresses subschema of VulcanStarter example-forms.
Commit 594bf423bc86aa83061b53866f6fcefa6415be03 introduced the error. When I reverse just this one commit, I am once again able to update nested fields.
=> bugfix - SmartForm cannot update nested input fields

packages/vulcan-ui-material/lib/components/forms/base-controls/MuiCheckbox.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiCheckboxGroup.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiInput.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiPicker.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiRadioGroup.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSelect.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSuggest.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSwitch.jsx
https://github.com/VulcanJS/Vulcan/commit/e42080ee0e9d09987c68e7b08c47fbef607499ab#diff-12f1ba5f1832fbef254275e160b2ad62
So the above commit denied of 8 different Mui form components their expected onChange function in props, changed it to handleChange
=> change Mui to expect handleChange in props

packages/vulcan-lib/lib/client/auth.js, packages/vulcan-lib/lib/modules/components.js, packages/vulcan-users/lib/modules/permissions.js
* `meteor_login_token` was not set with the correct sameSite attribute
* `instantiateComponent()` did not handle `React.forwardRef` components correctly
* `restrictDocument()` would fail for nested fields without a fieldSchema
=> Jun2020BugFixes1

packages/vulcan-lib/lib/client/auth.js
fix for: on localhost, on chrome, after refreshing the browser, user will get logged out
see: https://github.com/reactivestack/cookies/issues/233
=> change cookie secure to false on localhost

packages/vulcan-forms/lib/components/FormNestedArray.jsx
Add the option to have a nested schema on mount, this way the user doesn't have to click the + button in order to add the first item, he/she can just start typing in the data.
```
itemProperties: {
openNested: true
}
````
=> add itemProperties openNested option for nested schema

packages/vulcan-forms/lib/components/Form.jsx
When I open multiple SmartForms, submit one submits all forms.
For example, I open a first form to edit/create an object, then open another form to create another object to fill the first form.
As the SmartForm id prop is passed to the form node, I added a check for id equality between target and form in submitForm only if an id is passed to the smartForm.
=> Forms submit target verification

packages/vulcan-core/lib/modules/containers/create.js, packages/vulcan-core/lib/modules/containers/delete.js, packages/vulcan-core/lib/modules/containers/update.js
The generic create, update, and delete mutation (HoC/Hooks) wrappers would return their result in `response.data.<resolverName>`. This commit restored the name of those fields.
=> GenericMutationWrappersResponse

packages/vulcan-lib/lib/modules/graphql_templates/mutations.js, packages/vulcan-lib/lib/modules/graphql_templates/queries.js
`graphdoc` trips up on the format of some of the comments in `schema.graphql`
=> GraphQLComments

packages/vulcan-lib/lib/modules/components.js
Minor change to the JSDoc comments for registerComponent to avoid eslint warnings.
=> RegisterComponentJSDoc

packages/vulcan-ui-material/lib/components/bonus/DatatableFromArray.jsx, packages/vulcan-ui-material/lib/components/core/Datatable.jsx, packages/vulcan-ui-material/lib/components/index.js
* New `SearchInputProps` and `TableProps` props allow sending props to the `SearchInput` and `Table` components
* New `wrapComponent` prop allows overriding the scroller that the `Table` is wrapped in by default
* New `cellStyle` prop of column definitions accepts a function or object to add style to individual cells
* Added default value for `paginationTerms`
* New bonus component `DatatableFromArray` is a wrapper for `Datatable` that takes an array of objects and supports pagination
=> MuiDatatableUpgrades

packages/vulcan-lib/lib/modules/components.js, packages/vulcan-ui-material/history.md, packages/vulcan-ui-material/lib/components/forms/base-controls/EndAdornment.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiFormControl.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSelect.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/mixins/component.jsx
* EndAdornment: refactored the menu indicator
* MuiFormControl: new `layout` prop value of 'shrink' turns off the `fullWidth` option for the control
* MuiSelect: added clear button to select controls the same as input and suggest controls
* MuiSwitch: added support for `addonBefore` and `addonAfter` the same as input and suggest controls
* Fixed bug in in `instantiateComponent` that prevented React from reusing the component
=> MaterialUiMinorChanges7

packages/vulcan-ui-material/lib/components/ui/Modal.jsx, packages/vulcan-ui-material/lib/components/ui/ModalTrigger.jsx, packages/vulcan-ui-material/lib/modules/sampleTheme.js
* Removed bottom border when `Modal` dialog title is empty
* Moved `closeButton` style to `theme.utils`
* New `dontWrapDialogContent` prop prevents wrapping the children in a `DialogContent` component
* `DialogTrigger`'s content is now lazy rendered
* Added deprecation warning: __ModalTrigger’s "dialogProperties" prop has been renamed "dialogProps"__
=> MuiModalChanges

packages/vulcan-i18n-en-us/lib/en_US.js, packages/vulcan-i18n-es-es/lib/es_ES.js, packages/vulcan-i18n-fa-ir/lib/fa_IR.js, packages/vulcan-i18n-fr-fr/lib/fr_FR.js, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiPicker.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/StartAdornment.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Email.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Url.jsx, packages/vulcan-ui-material/lib/components/index.js
The value of `url` and `email` type inputs are scrubbed to make sure they output a valid url; `url`, `email`, and `social` type inputs display an active link
=> FormInputUrlMailSocialScrubbing

packages/vulcan-lib/lib/modules/validation.js, packages/vulcan-users/lib/modules/permissions.js
* `validateDocumentPermissions` would throw an error when the document field was `isNested` but had no `fieldSchema`
* This is the case for a nested schema that has a graphql-only field generated using `resolveAs`
* This will be better handled once people start using apiSchema Fields
=> Validate document permissions bug fix

packages/vulcan-accounts/imports/helpers.js
Instead of `Symbol()`, `Symbol.for()` will allow global access to Symbols like `STATES.SIGN_IN` in the other files in a two-repo Vulcan install. This allows customization (i.e. `replaceComponent`) of the `AccountsStateSwitcher`, for example.
More info on `Symbol.for()` from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol: 
> the Symbol() function will not create a global symbol that is available in your whole codebase. To create symbols available across files ... use the method Symbol.for()...
On the other hand, if there is no use of the `STATES` const outside of this `helpers.js` file, I believe there is no harm in using the global Symbol registry anyway.
=> Use Symbol.for for vulcan-accounts const STATES

packages/vulcan-lib/lib/modules/ui_utils.js
The placeholder from inputProperties gets removed when whitelistInputProps() is called in FormComponentInner.jsx, so placeholders get removed from smartform text inputs. This adds placeholder to the whitelist of supported fields so they are once again shown on Smartforms.
=> Add placeholder to the whitelist

packages/vulcan-lib/lib/modules/collections.js, packages/vulcan-lib/lib/modules/validation.js, packages/vulcan-lib/lib/server/default_resolvers.js, packages/vulcan-lib/lib/server/default_resolvers2.js
* Updated JSDoc comments for `Mongo.Collection.prototype.addField()` and fixed a minor bug.
* Updated `validateModifier()` to include `documentId` in the context of custom field validators. Validators can use it to make sure that a value is unique in the collection. Without the `documentId`, the validator can't tell if an existing document with a unique value is being updated or if a new document with a conflicting value is attempted to be inserted.
* Updated default resolvers to include the collection name when throwing a `missing_document` error.
=> Minor Data Layer Fixes Oct 2020

packages/vulcan-core/lib/modules/containers/multi.js, packages/vulcan-core/lib/modules/containers/multi2.js
`withMulti`, `useMulti`, `withMulti2`, `useMulti2` should return all the props from Apollo Client's `useQuery`, including `startPolling`, `stopPolling`, etc.
=> Multi HoC/Hook Returned Props

packages/vulcan-ui-material/en_US.js, packages/vulcan-ui-material/history.md, packages/vulcan-ui-material/lib/components/bonus/ScrollTrigger.jsx, packages/vulcan-ui-material/lib/components/bonus/TooltipButton.jsx, packages/vulcan-ui-material/lib/components/core/Datatable.jsx, packages/vulcan-ui-material/lib/components/forms/FormSubmit.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/EndAdornment.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiFormHelper.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiInput.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSelect.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiSuggest.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/StartAdornment.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/mixins/component.jsx, packages/vulcan-ui-material/lib/components/forms/controls/countries.js, packages/vulcan-ui-material/lib/components/theme/ThemeStyles.jsx, packages/vulcan-ui-material/lib/components/ui/ModalTrigger.jsx, packages/vulcan-ui-material/package.js, packages/vulcan-ui-material/readme.md
* MuiSuggest
* Fixed how styles are applied for focused, disabled, and error states
* Enabled the styling of `menuItem`, `menuItemHighlight`, and `menuItemIcon` classes
* Renamed `muiIcon` class to `selectIcon`
* Fixed a bug when `disableSelectOnBlur` prop was passed
* Tweaked the behavior of `highlightFirstSuggestion()`
* Added support for `inputRef` prop
* MuiInput: Previously the field value was not updated until the user exited the input (`blur` event); now the value is updated as you type, enabling the form submit button sooner
* Various components: Changed the type of component props to `PropTypes.oneOfType([PropTypes.node, PropTypes.elementType])`
* Various components: Updated spacing to comply with linting rules
* ScrollTrigger: Refined functionality
* TooltipButton: Changed …
=> Material UI Minor Updates Oct 2020

packages/vulcan-debug/lib/modules/callbacks/schema.js, packages/vulcan-debug/lib/modules/emails/schema.js, packages/vulcan-debug/lib/modules/permissions.js, packages/vulcan-debug/lib/modules/settings/schema.js
Package: vulcan:debug
The previous permissions were `['admins']` which is problematic when you're not logged in. So now I've set it to `['guests', 'members']` (I was not sure that if you're logged, you're still part of the guests group). I also factorized it a little, putting all inside a single variable, located in a `permissions` file.
=> update permissions for debug schemas

packages/vulcan-ui-material/lib/components/forms/FormGroupDefault.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/EndAdornment.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiCheckbox.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/MuiInput.jsx, packages/vulcan-ui-material/lib/components/forms/base-controls/SwitchBase.jsx, packages/vulcan-ui-material/lib/components/forms/controls/Checkbox.jsx
* MuiInput: Improved the debounce functionality and fixed some edge cases
* EndAdornment: Fixed bug: When the form control had an empty value the clear button would be hidden, but it was not disabled
* MuiCheckbox: Added support for start and end adornment in the checkbox base control and added additional classes that can be overridden for cusomization
* MuiSwitch: Renamed `MuiSwitch` component to `SwitchBase` because its name conflicted with the style sheet name of the core `Switch` component - we should rename all components in `vulcan:ui-material` that start with Mui
=> Material UI Minor Updates Nov 2020

packages/vulcan-i18n/lib/modules/provider.js, packages/vulcan-lib/lib/modules/intl.js
* Added support for pluralization in i18n strings using [ICU Message syntax used by react-intl](https://formatjs.io/docs/core-concepts/icu-syntax/#plural-format)
* Changed the `values` parameter of `IntlProvider.formatMessage` optional
=> i18n Plural Support

packages/vulcan-forms/lib/components/Form.jsx, packages/vulcan-forms/lib/components/propTypes.js
Smartform can now take an `initCallback` prop, similar to the `changeCallback` prop.
This initCallback runs on form init and on form "reset".
I'm doing a component that has a preview of the object currently edited, for that I need to get the form's current document. I realized that `changeCallback` did not run on init, so my preview was empty until i changed something to the form, triggering the change.
=> add init callback to smartform

packages/vulcan-lib/lib/modules/intl.js, packages/vulcan-lib/test/index.js, packages/vulcan-lib/test/intl.test.js
* In the values object you pass to `getString()` you can now use React nodes, in addition to simple strings, enabling the embedding of HTML tags, images, etc.
* Activated unit tests for `vulcan:lib/intl/formatLabel`
* Added unit tests for `vulcan:lib/intl/getString`
=> React Node Support in getString()

packages/vulcan-core/lib/modules/components/App.jsx, packages/vulcan-lib/lib/server/apollo-server/context.js
This is for the RTL Support the ticket I have created https://github.com/VulcanJS/Vulcan/issues/2669
Could you please check it carefully, as I don't have slightest idea about the impacts, but it's working fine on my local project for translations of StateOfJS ;) 
https://github.com/StateOfJS/state-of-js-graphql-results-api/issues/50
After checking the code, I had come to the conclusion that without this, the RTL support was not possible at all.
This is just the beginning and give the developer the opportunity by usage of RTL class in HTML to do custom CSS if needed ;)
=> Feature RTL support in locale

packages/vulcan-core/lib/modules/decorators/autocomplete.js, packages/vulcan-lib/lib/modules/mongoParams.js, packages/vulcan-lib/lib/modules/utils.js, packages/vulcan-lib/lib/server/graphql/typedefs.js, packages/vulcan-lib/test/mongoParams.test.js, packages/vulcan-lib/test/utils.test.js
* Enabled (uncommented) various query filter options in `String_Selector`, `String_Array_Selector`, `Int_Selector`, `Int_Array_Selector`, `Float_Selector`, `Float_Array_Selector`, `Boolean_Selector`, `Boolean_Array_Selector`, `Date_Selector`, `Date_Array_Selector`
* Added unit tests for vulcan:lib/mongoParams
=> Query filters to mongo params

packages/vulcan-core/lib/modules/components/AccessControl.jsx, packages/vulcan-core/lib/modules/components/App.jsx, packages/vulcan-core/lib/modules/components/Flash.jsx, packages/vulcan-core/lib/modules/components/FlashMessages.jsx, packages/vulcan-core/lib/modules/containers/withAccess.js, packages/vulcan-core/lib/modules/containers/withMessages.js, packages/vulcan-core/lib/modules/index.js, packages/vulcan-core/lib/modules/messages.js, packages/vulcan-i18n/lib/modules/context.js, packages/vulcan-i18n/lib/modules/index.js, packages/vulcan-i18n/lib/modules/useIntl.js, packages/vulcan-lib/lib/client/apollo-client/links/error.js, packages/vulcan-ui-material/lib/components/core/Flash.jsx, packages/vulcan-ui-material/lib/components/index.js
* An adaptation of Vulcan's flash message system, but using reactive state instead of React context
* Updated `withMessages` to use reactive state
* Added new `useMessages` hook
* Added new `useIntl` hook
* Separated `FlashMessages` component into its own file
* Updated `Flash` component to use reactive state
* Moved `getProperties()` from the Flash component to `normalizeMessage()` in withMessages
* Added new Material UI implementation of the `Flash` component
* Removed `messages` from the state of the `App` component, `MessageContext` from the component tree, and the methods `UNSAFE_componentWillMount`, `componentWillUnmount`, `flash`, and `clear`
* Removed `messages.js`, which only defined `MessageContext`
* Updated `error.js` to report the http status of network errors thrown by …
=> Flash messages in reactive state

packages/vulcan-lib/lib/server/apollo-server/context.js
Simply add a server-side callback called `graphql.context` that lets us iterate and modify the context passed to resolvers. It will run once per request, at graphql context initialization.
=> add graphql.context callback

packages/vulcan-forms/lib/components/Form.jsx, packages/vulcan-forms/lib/components/FormComponent.jsx, packages/vulcan-lib/lib/modules/intl.js, packages/vulcan-ui-material/lib/components/forms/base-controls/FormInput.jsx
* Fixed bug: `SmartForm.initField()` set each field's `document` property to the initial document, instead of the current document, resulting in bugs like [Nested Schema document update not working](https://github.com/VulcanJS/Vulcan/issues/2686)
* Fixed bug: `FormComponent.getDerivedStateFromProps()` would fail when `intlOrRegularValue` was null (because `typeof null === 'object'`); it's possible that this should not normally occur, but it has occurred in my codebase because of Invariant Violation errors thrown by Apollo, likely because we have not upgraded to Apollo Client 3 cache
* Fixed bug: Material UI Number input would not behave correctly when the user entered "0." quickly (the period would disappear)
* Fixed bug: Creating a new document with SmartForm would fail when no Apollo …
=> SmartForm minor bug fixes Jan 2020

packages/vulcan-lib/lib/server/connectors/mongo.js
Adds a callback to Connector.filter, which allows to iterate on the `selector`, `options` and `filteredFields` used in a collection's multi query.
=> Connector filter calbacks

packages/vulcan-ui-material/history.md, packages/vulcan-ui-material/lib/client/wrapWithMuiTheme.jsx, packages/vulcan-ui-material/lib/components/index.js, packages/vulcan-ui-material/lib/components/theme/ThemeProvider.jsx, packages/vulcan-ui-material/lib/server/wrapWithMuiTheme.jsx, packages/vulcan-ui-material/package.js, packages/vulcan-ui-material/readme.md
Also pass context on serverside.
The Client version of wrapWithMuiTheme was using Components.ThemeProvider while the server version was using the default ThemeProvider, so you could overwrite it client-side but not server-side. 
I introduced this three years ago in a [PR to ErikDakoda's package](https://github.com/ErikDakoda/vulcan-material-ui/pull/30)).
Now both the server and the client ThemeProvider uses the Components system, so they can be overwritten. The implementation for the default ThemeProvider was the same on client and server, so I implemented it directly in the `components/theme` folder which is common to both server and client environments.
Also, I add the `apolloClient` prop that lets you query data right inside the ThemeProvider to be able to have a dynamic theme …
=> Unify Server and Client ThemeProviders and pass apolloClient as prop

.storybook/webpack.config.js
The use of the optional chaining `?.` in `component.jsx` stops storybook working, I added the babel plugin to make it work
https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-ui-material/lib/components/forms/base-controls/mixins/component.jsx
=> add to storybook plugin-proposal-optional-chaining to accept component.jsx

packages/vulcan-core/lib/modules/components/Card/Card.jsx, packages/vulcan-forms/lib/components/Form.jsx, packages/vulcan-forms/lib/components/FormSubmit.jsx
#2664 
Fixed permission check to show/hide the delete button on SmartForms.
Also fixed the permission check for the edit button on Cards (was missing the document to be able to check ownership).
=> Fixed issue #2664 + Fixed canUpdate on Card.jsx

packages/vulcan-lib/lib/server/apollo-server/context.js
Hi guys,
First time contributor and long time Meteor fan here. I couldn't find any guidelines regarding the PR process, so if I did something wrong please let me know.
As described in #2625, `getUser()` was copied from `meteor/apollo` and added the `export` keyword to `setupAuthToken()`.
Thanks!
=> Remove dependency to meteor/apollo getUser - Fixes issue #2625

packages/vulcan-users/lib/modules/schema.js
This update makes it so that user's display name can now be set as an 'extraField' during account sign up. Without the change, displayName is always overridden when provided as an extra field and there's no other way to set account name.
=> Update onCreate for Vulcan:Users schema.js `displayName`
